import { Appliance } from '@/types';

export const mockAppliances: Appliance[] = [
  // Rahul Sharma (CUST-1001)
  {
    id: 'APP-2001',
    customerId: 'CUST-1001',
    customerName: 'Rahul Sharma',
    customerPhone: '+91 98201 XXXXX',
    type: 'Washing Machine',
    brand: 'Samsung',
    model: 'WW80T504DAN',
    serialNumber: 'SN-SAMS-882910',
    capacity: '8.0 kg Front Load',
    purchaseDate: '15 March 2024',
    warranty: 'Active',
    warrantyExpiryDate: '14 March 2027',
    lastService: '18 September 2026',
    status: 'Under Service',
    notes: 'Inverter direct drive motor covered under 10-year warranty.',
  },
  {
    id: 'APP-2002',
    customerId: 'CUST-1001',
    customerName: 'Rahul Sharma',
    customerPhone: '+91 98201 XXXXX',
    type: 'Air Conditioner',
    brand: 'LG',
    model: 'KS-Q18ENZA',
    serialNumber: 'SN-LGAC-449102',
    capacity: '1.5 Ton 5-Star Dual Inverter',
    purchaseDate: '10 May 2024',
    warranty: 'Active',
    warrantyExpiryDate: '09 May 2026',
    lastService: '12 April 2026',
    status: 'Active',
    notes: 'Annual maintenance check completed in April.',
  },
  {
    id: 'APP-2003',
    customerId: 'CUST-1001',
    customerName: 'Rahul Sharma',
    customerPhone: '+91 98201 XXXXX',
    type: 'Refrigerator',
    brand: 'Whirlpool',
    model: 'IF INV CNV 278',
    serialNumber: 'SN-WHRL-193021',
    capacity: '265 Litres Double Door',
    purchaseDate: '20 August 2021',
    warranty: 'Expired',
    warrantyExpiryDate: '19 August 2023',
    lastService: '10 January 2025',
    status: 'Active',
    notes: 'Out of standard warranty; compressor warranty active.',
  },

  // Priya Mehta (CUST-1002)
  {
    id: 'APP-2004',
    customerId: 'CUST-1002',
    customerName: 'Priya Mehta',
    customerPhone: '+91 98114 XXXXX',
    type: 'Air Conditioner',
    brand: 'Daikin',
    model: 'FTKF50TV',
    serialNumber: 'SN-DAIK-773829',
    capacity: '1.5 Ton 3-Star Inverter',
    purchaseDate: '05 April 2024',
    warranty: 'Active',
    warrantyExpiryDate: '04 April 2026',
    lastService: '02 June 2026',
    status: 'Under Service',
    notes: 'Current service request active for cooling performance.',
  },
  {
    id: 'APP-2005',
    customerId: 'CUST-1002',
    customerName: 'Priya Mehta',
    customerPhone: '+91 98114 XXXXX',
    type: 'Water Purifier',
    brand: 'Kent',
    model: 'Grand Plus RO+UV+UF',
    serialNumber: 'SN-KENT-992013',
    capacity: '9 Litres Tank',
    purchaseDate: '12 November 2023',
    warranty: 'Active',
    warrantyExpiryDate: '11 November 2026',
    lastService: '10 May 2026',
    status: 'Active',
    notes: 'Sediment and carbon filters replaced during May service.',
  },

  // Amit Verma (CUST-1003)
  {
    id: 'APP-2006',
    customerId: 'CUST-1003',
    customerName: 'Amit Verma',
    customerPhone: '+91 98450 XXXXX',
    type: 'Television',
    brand: 'Sony',
    model: 'Bravia KD-55X74L',
    serialNumber: 'SN-SONY-654321',
    capacity: '55 Inch 4K Ultra HD Google TV',
    purchaseDate: '18 October 2024',
    warranty: 'Active',
    warrantyExpiryDate: '17 October 2026',
    lastService: '18 October 2024',
    status: 'Active',
    notes: 'Installation performed by authorized Sony center.',
  },
  {
    id: 'APP-2007',
    customerId: 'CUST-1003',
    customerName: 'Amit Verma',
    customerPhone: '+91 98450 XXXXX',
    type: 'Washing Machine',
    brand: 'IFB',
    model: 'Senator Smart Touch',
    serialNumber: 'SN-IFBW-332901',
    capacity: '8.5 kg Front Load',
    purchaseDate: '22 December 2023',
    warranty: 'Active',
    warrantyExpiryDate: '21 December 2027',
    lastService: '15 January 2026',
    status: 'Active',
    notes: '4-year comprehensive warranty active.',
  },
  {
    id: 'APP-2008',
    customerId: 'CUST-1003',
    customerName: 'Amit Verma',
    customerPhone: '+91 98450 XXXXX',
    type: 'Refrigerator',
    brand: 'LG',
    model: 'GL-T432APZY',
    serialNumber: 'SN-LGRF-128492',
    capacity: '398 Litres Double Door Inverter',
    purchaseDate: '14 January 2024',
    warranty: 'Active',
    warrantyExpiryDate: '13 January 2026',
    lastService: '14 January 2024',
    status: 'Active',
  },

  // Neha Kapoor (CUST-1004)
  {
    id: 'APP-2009',
    customerId: 'CUST-1004',
    customerName: 'Neha Kapoor',
    customerPhone: '+91 98102 XXXXX',
    type: 'Air Conditioner',
    brand: 'Voltas',
    model: '185V Vectra Elite',
    serialNumber: 'SN-VOLT-551920',
    capacity: '1.5 Ton 5-Star Split AC',
    purchaseDate: '01 June 2024',
    warranty: 'Active',
    warrantyExpiryDate: '31 May 2026',
    lastService: '12 March 2026',
    status: 'Under Service',
    notes: 'Customer reported intermittent cooling cycle.',
  },
  {
    id: 'APP-2010',
    customerId: 'CUST-1004',
    customerName: 'Neha Kapoor',
    customerPhone: '+91 98102 XXXXX',
    type: 'Washing Machine',
    brand: 'Bosch',
    model: 'Serie 6 WAT28461IN',
    serialNumber: 'SN-BSCH-771928',
    capacity: '8 kg Front Load',
    purchaseDate: '15 July 2024',
    warranty: 'Active',
    warrantyExpiryDate: '14 July 2027',
    lastService: '15 July 2024',
    status: 'Active',
  },
  {
    id: 'APP-2011',
    customerId: 'CUST-1004',
    customerName: 'Neha Kapoor',
    customerPhone: '+91 98102 XXXXX',
    type: 'Water Purifier',
    brand: 'Aquaguard',
    model: 'Geneus Active Copper',
    serialNumber: 'SN-AQUA-881290',
    capacity: '7 Litres RO+UV',
    purchaseDate: '20 August 2024',
    warranty: 'Active',
    warrantyExpiryDate: '19 August 2025',
    lastService: '10 February 2026',
    status: 'Active',
  },
  {
    id: 'APP-2012',
    customerId: 'CUST-1004',
    customerName: 'Neha Kapoor',
    customerPhone: '+91 98102 XXXXX',
    type: 'Television',
    brand: 'Samsung',
    model: 'QA65Q60CAKLXL',
    serialNumber: 'SN-SAMT-993821',
    capacity: '65 Inch QLED 4K Smart TV',
    purchaseDate: '28 October 2024',
    warranty: 'Active',
    warrantyExpiryDate: '27 October 2027',
    lastService: '28 October 2024',
    status: 'Active',
  },

  // Arjun Singh (CUST-1005)
  {
    id: 'APP-2013',
    customerId: 'CUST-1005',
    customerName: 'Arjun Singh',
    customerPhone: '+91 97170 XXXXX',
    type: 'Refrigerator',
    brand: 'Samsung',
    model: 'RT37C4512S8',
    serialNumber: 'SN-SAMR-332918',
    capacity: '324 Litres Frost Free',
    purchaseDate: '10 February 2025',
    warranty: 'Active',
    warrantyExpiryDate: '09 February 2027',
    lastService: '10 February 2025',
    status: 'Active',
  },
  {
    id: 'APP-2014',
    customerId: 'CUST-1005',
    customerName: 'Arjun Singh',
    customerPhone: '+91 97170 XXXXX',
    type: 'Air Conditioner',
    brand: 'Hitachi',
    model: 'RAW318HFDO',
    serialNumber: 'SN-HITA-448201',
    capacity: '1.5 Ton Window AC',
    purchaseDate: '15 March 2022',
    warranty: 'Expired',
    warrantyExpiryDate: '14 March 2024',
    lastService: '05 April 2025',
    status: 'Active',
  },

  // Sneha Patel (CUST-1006)
  {
    id: 'APP-2015',
    customerId: 'CUST-1006',
    customerName: 'Sneha Patel',
    customerPhone: '+91 98250 XXXXX',
    type: 'Washing Machine',
    brand: 'Whirlpool',
    model: '360 Bloomwash Pro',
    serialNumber: 'SN-WHLW-882739',
    capacity: '7.5 kg Top Load',
    purchaseDate: '11 August 2024',
    warranty: 'Active',
    warrantyExpiryDate: '10 August 2026',
    lastService: '11 August 2024',
    status: 'Under Service',
    notes: 'Reported water draining issue.',
  },
  {
    id: 'APP-2016',
    customerId: 'CUST-1006',
    customerName: 'Sneha Patel',
    customerPhone: '+91 98250 XXXXX',
    type: 'Water Purifier',
    brand: 'Kent',
    model: 'Prime Plus RO',
    serialNumber: 'SN-KENT-440291',
    capacity: '9 Litres',
    purchaseDate: '25 September 2024',
    warranty: 'Active',
    warrantyExpiryDate: '24 September 2025',
    lastService: '25 September 2024',
    status: 'Active',
  },

  // Vikram Malhotra (CUST-1007)
  {
    id: 'APP-2017',
    customerId: 'CUST-1007',
    customerName: 'Vikram Malhotra',
    customerPhone: '+91 98300 XXXXX',
    type: 'Air Conditioner',
    brand: 'Mitsubishi',
    model: 'MSY-JS18VF',
    serialNumber: 'SN-MITS-662910',
    capacity: '1.5 Ton Heavy Duty Inverter',
    purchaseDate: '18 April 2024',
    warranty: 'Active',
    warrantyExpiryDate: '17 April 2027',
    lastService: '10 June 2025',
    status: 'Active',
  },
  {
    id: 'APP-2018',
    customerId: 'CUST-1007',
    customerName: 'Vikram Malhotra',
    customerPhone: '+91 98300 XXXXX',
    type: 'Television',
    brand: 'LG',
    model: 'OLED55C3PSA',
    serialNumber: 'SN-LGO-992019',
    capacity: '55 Inch 4K OLED evo TV',
    purchaseDate: '12 May 2024',
    warranty: 'Active',
    warrantyExpiryDate: '11 May 2027',
    lastService: '12 May 2024',
    status: 'Active',
  },
  {
    id: 'APP-2019',
    customerId: 'CUST-1007',
    customerName: 'Vikram Malhotra',
    customerPhone: '+91 98300 XXXXX',
    type: 'Refrigerator',
    brand: 'Haier',
    model: 'HRB-3654POG-E',
    serialNumber: 'SN-HAI-771029',
    capacity: '328 Litres Bottom Mounted',
    purchaseDate: '01 June 2024',
    warranty: 'Active',
    warrantyExpiryDate: '31 May 2026',
    lastService: '01 June 2024',
    status: 'Active',
  },

  // Ananya Iyer (CUST-1008)
  {
    id: 'APP-2020',
    customerId: 'CUST-1008',
    customerName: 'Ananya Iyer',
    customerPhone: '+91 98401 XXXXX',
    type: 'Washing Machine',
    brand: 'LG',
    model: 'FHM1207SDW',
    serialNumber: 'SN-LGW-883902',
    capacity: '7 kg Fully Automatic Front Load',
    purchaseDate: '14 November 2024',
    warranty: 'Active',
    warrantyExpiryDate: '13 November 2026',
    lastService: '14 November 2024',
    status: 'Active',
  },
  {
    id: 'APP-2021',
    customerId: 'CUST-1008',
    customerName: 'Ananya Iyer',
    customerPhone: '+91 98401 XXXXX',
    type: 'Air Conditioner',
    brand: 'Carrier',
    model: 'CAI18ER3R30F0',
    serialNumber: 'SN-CARR-552810',
    capacity: '1.5 Ton 3-Star Inverter AC',
    purchaseDate: '05 December 2024',
    warranty: 'Active',
    warrantyExpiryDate: '04 December 2025',
    lastService: '05 December 2024',
    status: 'Under Service',
    notes: 'Indoor unit water dripping complaint.',
  },
  {
    id: 'APP-2022',
    customerId: 'CUST-1008',
    customerName: 'Ananya Iyer',
    customerPhone: '+91 98401 XXXXX',
    type: 'Water Purifier',
    brand: 'Pureit',
    model: 'Copper+ Mineral RO',
    serialNumber: 'SN-PURE-229103',
    capacity: '8 Litres',
    purchaseDate: '10 January 2025',
    warranty: 'Active',
    warrantyExpiryDate: '09 January 2026',
    lastService: '10 January 2025',
    status: 'Active',
  },

  // Rohan Deshmukh (CUST-1009)
  {
    id: 'APP-2023',
    customerId: 'CUST-1009',
    customerName: 'Rohan Deshmukh',
    customerPhone: '+91 98220 XXXXX',
    type: 'Refrigerator',
    brand: 'Samsung',
    model: 'RT28C3733S8',
    serialNumber: 'SN-SAMR-991048',
    capacity: '236 Litres Double Door',
    purchaseDate: '08 May 2025',
    warranty: 'Active',
    warrantyExpiryDate: '07 May 2027',
    lastService: '08 May 2025',
    status: 'Active',
  },
  {
    id: 'APP-2024',
    customerId: 'CUST-1009',
    customerName: 'Rohan Deshmukh',
    customerPhone: '+91 98220 XXXXX',
    type: 'Television',
    brand: 'OnePlus',
    model: '50 Y1S Pro',
    serialNumber: 'SN-1PLS-449102',
    capacity: '50 Inch 4K UHD LED Android TV',
    purchaseDate: '15 June 2025',
    warranty: 'Active',
    warrantyExpiryDate: '14 June 2026',
    lastService: '15 June 2025',
    status: 'Active',
  },

  // Kavita Reddy (CUST-1010)
  {
    id: 'APP-2025',
    customerId: 'CUST-1010',
    customerName: 'Kavita Reddy',
    customerPhone: '+91 98490 XXXXX',
    type: 'Air Conditioner',
    brand: 'Blue Star',
    model: 'IC318EBTU',
    serialNumber: 'SN-BLUS-112093',
    capacity: '1.5 Ton 3-Star Inverter AC',
    purchaseDate: '19 December 2024',
    warranty: 'Active',
    warrantyExpiryDate: '18 December 2025',
    lastService: '19 December 2024',
    status: 'Under Service',
    notes: 'Remote control not syncing with indoor unit.',
  },
  {
    id: 'APP-2026',
    customerId: 'CUST-1010',
    customerName: 'Kavita Reddy',
    customerPhone: '+91 98490 XXXXX',
    type: 'Washing Machine',
    brand: 'Samsung',
    model: 'WA65A4002VS',
    serialNumber: 'SN-SAMW-883019',
    capacity: '6.5 kg Top Load',
    purchaseDate: '24 January 2025',
    warranty: 'Active',
    warrantyExpiryDate: '23 January 2028',
    lastService: '24 January 2025',
    status: 'Active',
  },
  {
    id: 'APP-2027',
    customerId: 'CUST-1010',
    customerName: 'Kavita Reddy',
    customerPhone: '+91 98490 XXXXX',
    type: 'Water Purifier',
    brand: 'Livpure',
    model: 'Glo Star RO+UV',
    serialNumber: 'SN-LIVP-774019',
    capacity: '7 Litres',
    purchaseDate: '02 February 2025',
    warranty: 'Active',
    warrantyExpiryDate: '01 February 2026',
    lastService: '02 February 2025',
    status: 'Active',
  },
  {
    id: 'APP-2028',
    customerId: 'CUST-1010',
    customerName: 'Kavita Reddy',
    customerPhone: '+91 98490 XXXXX',
    type: 'Refrigerator',
    brand: 'Godrej',
    model: 'RT EONVALOR 260B',
    serialNumber: 'SN-GODR-553018',
    capacity: '244 Litres Frost Free',
    purchaseDate: '10 March 2025',
    warranty: 'Active',
    warrantyExpiryDate: '09 March 2026',
    lastService: '10 March 2025',
    status: 'Active',
  },

  // Manoj Kumar (CUST-1011)
  {
    id: 'APP-2029',
    customerId: 'CUST-1011',
    customerName: 'Manoj Kumar',
    customerPhone: '+91 98188 XXXXX',
    type: 'Television',
    brand: 'Xiaomi',
    model: 'Smart TV X Series 43',
    serialNumber: 'SN-MI-662910',
    capacity: '43 Inch 4K Dolby Vision',
    purchaseDate: '14 July 2024',
    warranty: 'Active',
    warrantyExpiryDate: '13 July 2025',
    lastService: '14 July 2024',
    status: 'Active',
  },
  {
    id: 'APP-2030',
    customerId: 'CUST-1011',
    customerName: 'Manoj Kumar',
    customerPhone: '+91 98188 XXXXX',
    type: 'Washing Machine',
    brand: 'Whirlpool',
    model: 'Stainwash Ultra',
    serialNumber: 'SN-WHLW-229104',
    capacity: '8.0 kg Fully Automatic',
    purchaseDate: '20 August 2024',
    warranty: 'Active',
    warrantyExpiryDate: '19 August 2026',
    lastService: '20 August 2024',
    status: 'Active',
  },

  // Divya Nair (CUST-1012)
  {
    id: 'APP-2031',
    customerId: 'CUST-1012',
    customerName: 'Divya Nair',
    customerPhone: '+91 98470 XXXXX',
    type: 'Refrigerator',
    brand: 'LG',
    model: 'GL-S292RDSY',
    serialNumber: 'SN-LGR-991048',
    capacity: '242 Litres Smart Inverter',
    purchaseDate: '15 January 2025',
    warranty: 'Active',
    warrantyExpiryDate: '14 January 2026',
    lastService: '15 January 2025',
    status: 'Under Service',
    notes: 'Excessive frost buildup on freezer walls.',
  },

  // Pooja Agarwal (CUST-1014)
  {
    id: 'APP-2032',
    customerId: 'CUST-1014',
    customerName: 'Pooja Agarwal',
    customerPhone: '+91 98390 XXXXX',
    type: 'Water Purifier',
    brand: 'Kent',
    model: 'Supreme Alkaline RO',
    serialNumber: 'SN-KENT-771920',
    capacity: '8 Litres',
    purchaseDate: '12 October 2024',
    warranty: 'Active',
    warrantyExpiryDate: '11 October 2025',
    lastService: '12 October 2024',
    status: 'Under Service',
    notes: 'Beeping error alarm continuous.',
  },
];
