import { Call } from '@/types';

export const mockCalls: Call[] = [
  // Live Active Calls (Currently in progress)
  {
    id: 'CALL-83921',
    customerId: 'CUST-1001',
    customerName: 'Rahul Sharma',
    customerPhone: '+91 98201 XXXXX',
    appliance: 'Washing Machine',
    applianceId: 'APP-2001',
    intent: 'Product Issue',
    issue: 'Excessive vibration during spin cycle',
    duration: '02:18',
    durationSeconds: 138,
    sentiment: 'Frustrated',
    outcome: 'Service Request Created',
    priority: 'Medium',
    aiState: 'Listening',
    aiConfidence: 94,
    date: 'Today, 20:18',
    isLive: true,
    currentAction: 'Creating Service Request...',
    transcript: [
      {
        id: 'msg-1',
        speaker: 'ai',
        message: 'Welcome to HomeCare. How can I help you today?',
        timestamp: '00:03',
        confidence: 99,
      },
      {
        id: 'msg-2',
        speaker: 'customer',
        message: 'My washing machine is making a very loud noise.',
        timestamp: '00:24',
      },
      {
        id: 'msg-3',
        speaker: 'ai',
        message: 'I can help you with that. Does the machine also move or vibrate during the spin cycle?',
        timestamp: '00:46',
        confidence: 96,
      },
      {
        id: 'msg-4',
        speaker: 'customer',
        message: 'Yes, it moves quite a lot and vibrates aggressively on high speed.',
        timestamp: '01:15',
      },
      {
        id: 'msg-5',
        speaker: 'ai',
        message: 'Thank you for confirming that, Mr. Sharma. Based on your description, the drum suspension damper needs checking. I am creating a service request for an authorized technician to inspect your Samsung 8kg front load washing machine.',
        timestamp: '01:48',
        confidence: 95,
      },
      {
        id: 'msg-6',
        speaker: 'customer',
        message: 'Okay, will they be able to come tomorrow morning?',
        timestamp: '02:08',
      },
    ],
    analysis: {
      intent: 'Product Issue',
      appliance: 'Washing Machine',
      issue: 'Excessive vibration during spin cycle',
      sentiment: 'Frustrated',
      priority: 'Medium',
      confidence: 94,
      summary: 'Customer reported excessive vibration from a washing machine during the spin cycle. Customer confirmed that the appliance moves significantly during operation. AI determined that a technician inspection is required and initiated service request SR-10482.',
    },
    actionsTaken: [
      { id: 'act-1', action: 'CHECK_CUSTOMER', description: 'Customer identified via caller ID (+91 98201 XXXXX)', completed: true, timestamp: '00:05' },
      { id: 'act-2', action: 'CHECK_APPLIANCE', description: 'Appliance identified: Samsung WW80T504DAN', completed: true, timestamp: '00:28' },
      { id: 'act-3', action: 'CHECK_WARRANTY', description: 'Warranty verified: Active until March 2027', completed: true, timestamp: '00:48' },
      { id: 'act-4', action: 'CREATE_SERVICE_REQUEST', description: 'Service request created: SR-10482', completed: true, timestamp: '01:50' },
      { id: 'act-5', action: 'SEND_CONFIRMATION', description: 'Customer confirmation provided and SMS dispatch scheduled', completed: false, timestamp: 'Pending' },
    ],
  },
  {
    id: 'CALL-83922',
    customerId: 'CUST-1002',
    customerName: 'Priya Mehta',
    customerPhone: '+91 98114 XXXXX',
    appliance: 'Air Conditioner',
    applianceId: 'APP-2004',
    intent: 'Product Issue',
    issue: 'AC running but blowing room temperature air',
    duration: '01:42',
    durationSeconds: 102,
    sentiment: 'Frustrated',
    outcome: 'Service Request Created',
    priority: 'High',
    aiState: 'Taking Action',
    aiConfidence: 96,
    date: 'Today, 20:19',
    isLive: true,
    currentAction: 'Scheduling Technician Inspection...',
    transcript: [
      {
        id: 'msg-21',
        speaker: 'ai',
        message: 'Thank you for calling HomeCare support. How can I assist you today, Ms. Mehta?',
        timestamp: '00:02',
      },
      {
        id: 'msg-22',
        speaker: 'customer',
        message: 'Hello, my Daikin split AC in the master bedroom is not cooling. The fan is blowing air, but it is not cold at all.',
        timestamp: '00:22',
      },
      {
        id: 'msg-23',
        speaker: 'ai',
        message: 'I understand how inconvenient that is in this heat. Can you check if the outdoor unit is making a humming sound when you turn the temperature down to 18 degrees?',
        timestamp: '00:45',
      },
      {
        id: 'msg-24',
        speaker: 'customer',
        message: 'I just stepped out to the balcony. No, the outdoor fan is not spinning at all.',
        timestamp: '01:14',
      },
      {
        id: 'msg-25',
        speaker: 'ai',
        message: 'Got it. That indicates either a capacitor or compressor trigger fault. I am immediately generating a high-priority technician visit under your active warranty.',
        timestamp: '01:35',
      },
    ],
    analysis: {
      intent: 'Product Issue',
      appliance: 'Air Conditioner',
      issue: 'Not cooling (outdoor compressor not engaging)',
      sentiment: 'Frustrated',
      priority: 'High',
      confidence: 96,
      summary: 'Customer reported Daikin 1.5T AC running without cooling. Verified outdoor unit fan and compressor are inactive. Created high-priority service request SR-10481.',
    },
    actionsTaken: [
      { id: 'act-21', action: 'CHECK_CUSTOMER', description: 'Identified Priya Mehta (New Delhi)', completed: true, timestamp: '00:03' },
      { id: 'act-22', action: 'CHECK_APPLIANCE', description: 'Matched Daikin FTKF50TV (APP-2004)', completed: true, timestamp: '00:24' },
      { id: 'act-23', action: 'CHECK_WARRANTY', description: 'Warranty confirmed Active through April 2026', completed: true, timestamp: '00:46' },
      { id: 'act-24', action: 'CREATE_SERVICE_REQUEST', description: 'Created SR-10481 (High Priority)', completed: true, timestamp: '01:38' },
    ],
  },
  {
    id: 'CALL-83923',
    customerId: 'CUST-1004',
    customerName: 'Neha Kapoor',
    customerPhone: '+91 98102 XXXXX',
    appliance: 'Air Conditioner',
    applianceId: 'APP-2009',
    intent: 'Product Issue',
    issue: 'Voltas AC displays E4 error code',
    duration: '00:54',
    durationSeconds: 54,
    sentiment: 'Neutral',
    outcome: 'Resolved by AI',
    priority: 'Medium',
    aiState: 'Thinking',
    aiConfidence: 91,
    date: 'Today, 20:20',
    isLive: true,
    currentAction: 'Querying Knowledge Base for E4 Error...',
    transcript: [
      {
        id: 'msg-31',
        speaker: 'ai',
        message: 'Welcome to HomeCare VIP support. How may I assist you today, Ms. Kapoor?',
        timestamp: '00:02',
      },
      {
        id: 'msg-32',
        speaker: 'customer',
        message: 'Hi, my Voltas AC just beeped and the display is flashing E4.',
        timestamp: '00:18',
      },
      {
        id: 'msg-33',
        speaker: 'ai',
        message: 'Allow me a moment to check the error code reference for the Voltas Vectra Elite series.',
        timestamp: '00:36',
      },
    ],
    analysis: {
      intent: 'Product Issue',
      appliance: 'Air Conditioner',
      issue: 'Voltas E4 error code (Indoor temperature sensor or airflow block)',
      sentiment: 'Neutral',
      priority: 'Medium',
      confidence: 91,
      summary: 'Customer called regarding E4 code on Voltas AC. AI is executing knowledge retrieval to provide self-diagnostic steps.',
    },
    actionsTaken: [
      { id: 'act-31', action: 'CHECK_CUSTOMER', description: 'Customer identified: Neha Kapoor (VIP Tier)', completed: true, timestamp: '00:04' },
      { id: 'act-32', action: 'CHECK_APPLIANCE', description: 'Selected Voltas 185V Vectra Elite', completed: true, timestamp: '00:20' },
    ],
  },
  {
    id: 'CALL-83924',
    customerId: 'CUST-1008',
    customerName: 'Ananya Iyer',
    customerPhone: '+91 98401 XXXXX',
    appliance: 'Air Conditioner',
    applianceId: 'APP-2021',
    intent: 'Product Issue',
    issue: 'Water dripping continuously from indoor AC unit',
    duration: '03:12',
    durationSeconds: 192,
    sentiment: 'Frustrated',
    outcome: 'Human Escalation',
    priority: 'High',
    aiState: 'Escalated',
    aiConfidence: 78,
    date: 'Today, 20:17',
    isLive: true,
    currentAction: 'Transferring to Senior Support Specialist...',
    transcript: [
      {
        id: 'msg-41',
        speaker: 'ai',
        message: 'Welcome to HomeCare. How can I help you today?',
        timestamp: '00:02',
      },
      {
        id: 'msg-42',
        speaker: 'customer',
        message: 'There is water leaking inside my bedroom from the AC unit! It is ruining the wooden floor.',
        timestamp: '00:25',
      },
      {
        id: 'msg-43',
        speaker: 'ai',
        message: 'I understand this is urgent, Ms. Iyer. Please turn off the AC power immediately from the main circuit switch to prevent electrical hazard.',
        timestamp: '00:52',
      },
      {
        id: 'msg-44',
        speaker: 'customer',
        message: 'I have turned it off, but I need someone here right away! Put me through to a manager.',
        timestamp: '01:30',
      },
      {
        id: 'msg-45',
        speaker: 'ai',
        message: 'I am immediately escalating your call to our Senior Emergency Dispatch team with all your appliance and address details.',
        timestamp: '02:05',
      },
    ],
    analysis: {
      intent: 'Human Agent',
      appliance: 'Air Conditioner',
      issue: 'Severe water leakage from indoor unit onto wooden flooring',
      sentiment: 'Frustrated',
      priority: 'High',
      confidence: 78,
      summary: 'Emergency indoor water leakage. Customer demanded immediate human escalation. Advised power cutoff and transferred to senior support.',
    },
    actionsTaken: [
      { id: 'act-41', action: 'CHECK_CUSTOMER', description: 'Customer identified: Ananya Iyer', completed: true, timestamp: '00:04' },
      { id: 'act-42', action: 'CHECK_APPLIANCE', description: 'Carrier Inverter Split AC (APP-2021)', completed: true, timestamp: '00:30' },
      { id: 'act-43', action: 'ESCALATE_HUMAN', description: 'Escalated to human supervisor due to customer request & water damage risk', completed: true, timestamp: '02:10' },
    ],
  },
  {
    id: 'CALL-83925',
    customerId: 'CUST-1006',
    customerName: 'Sneha Patel',
    customerPhone: '+91 98250 XXXXX',
    appliance: 'Washing Machine',
    applianceId: 'APP-2015',
    intent: 'Product Issue',
    issue: 'Water not draining from drum',
    duration: '01:12',
    durationSeconds: 72,
    sentiment: 'Neutral',
    outcome: 'Service Request Created',
    priority: 'Medium',
    aiState: 'Listening',
    aiConfidence: 95,
    date: 'Today, 20:19',
    isLive: true,
    currentAction: 'Assessing Drain Pump Filter Status...',
    transcript: [
      {
        id: 'msg-51',
        speaker: 'ai',
        message: 'Hello, welcome to HomeCare customer support. How can I help you today?',
        timestamp: '00:02',
      },
      {
        id: 'msg-52',
        speaker: 'customer',
        message: 'My Whirlpool washing machine has stopped draining water. The clothes are soaked in soap water.',
        timestamp: '00:30',
      },
      {
        id: 'msg-53',
        speaker: 'ai',
        message: 'I can help with that. Is there an error code shown on the display, like E2 or OE?',
        timestamp: '00:58',
      },
    ],
    analysis: {
      intent: 'Product Issue',
      appliance: 'Washing Machine',
      issue: 'Drain pump blockage / clothes stuck in water',
      sentiment: 'Neutral',
      priority: 'Medium',
      confidence: 95,
      summary: 'Customer called for drain failure on Whirlpool Top Load. AI diagnostic question underway.',
    },
    actionsTaken: [
      { id: 'act-51', action: 'CHECK_CUSTOMER', description: 'Customer identified: Sneha Patel', completed: true, timestamp: '00:03' },
      { id: 'act-52', action: 'CHECK_APPLIANCE', description: 'Appliance identified: Whirlpool 360 Bloomwash', completed: true, timestamp: '00:35' },
    ],
  },
  {
    id: 'CALL-83926',
    customerId: 'CUST-1010',
    customerName: 'Kavita Reddy',
    customerPhone: '+91 98490 XXXXX',
    appliance: 'Water Purifier',
    applianceId: 'APP-2027',
    intent: 'Warranty',
    issue: 'Annual maintenance and filter replacement inquiry',
    duration: '01:05',
    durationSeconds: 65,
    sentiment: 'Positive',
    outcome: 'Resolved by AI',
    priority: 'Low',
    aiState: 'Taking Action',
    aiConfidence: 98,
    date: 'Today, 20:20',
    isLive: true,
    currentAction: 'Booking Filter Replacement Visit...',
    transcript: [
      {
        id: 'msg-61',
        speaker: 'ai',
        message: 'Welcome to HomeCare support. How can I help you today, Mrs. Reddy?',
        timestamp: '00:02',
      },
      {
        id: 'msg-62',
        speaker: 'customer',
        message: 'Hello, my RO filter beeped for maintenance. Is my annual maintenance contract still valid?',
        timestamp: '00:25',
      },
      {
        id: 'msg-63',
        speaker: 'ai',
        message: 'Yes! Your Livpure Glo Star is under comprehensive warranty until February 2026. This includes free annual filter replacement. Shall I book an engineer visit for this Thursday?',
        timestamp: '00:48',
      },
      {
        id: 'msg-64',
        speaker: 'customer',
        message: 'Yes please, Thursday between 10 AM and 1 PM works best.',
        timestamp: '01:02',
      },
    ],
    analysis: {
      intent: 'Warranty',
      appliance: 'Water Purifier',
      issue: 'Annual scheduled filter change covered under warranty',
      sentiment: 'Positive',
      priority: 'Low',
      confidence: 98,
      summary: 'Verified active warranty for customer. Scheduled free preventative maintenance filter replacement.',
    },
    actionsTaken: [
      { id: 'act-61', action: 'CHECK_CUSTOMER', description: 'Identified Kavita Reddy', completed: true, timestamp: '00:03' },
      { id: 'act-62', action: 'CHECK_WARRANTY', description: 'Warranty verified active (Free AMC)', completed: true, timestamp: '00:30' },
      { id: 'act-63', action: 'CREATE_SERVICE_REQUEST', description: 'Created routine filter replacement ticket', completed: true, timestamp: '01:04' },
    ],
  },

  // Historical Completed Calls (40+ items)
  {
    id: 'CALL-83920',
    customerId: 'CUST-1003',
    customerName: 'Amit Verma',
    customerPhone: '+91 98450 XXXXX',
    appliance: 'Television',
    applianceId: 'APP-2006',
    intent: 'Product Issue',
    issue: 'Sony Bravia TV sound working but black screen',
    duration: '02:45',
    durationSeconds: 165,
    sentiment: 'Neutral',
    outcome: 'Resolved by AI',
    priority: 'Medium',
    aiState: 'Completed',
    aiConfidence: 96,
    date: 'Today, 19:42',
    transcript: [
      { id: 'th-1', speaker: 'ai', message: 'Welcome to HomeCare. How may I assist you today, Mr. Verma?', timestamp: '00:02' },
      { id: 'th-2', speaker: 'customer', message: 'Hello, my Sony Bravia 55 inch TV has audio playing from Netflix, but the screen is completely pitch black.', timestamp: '00:25' },
      { id: 'th-3', speaker: 'ai', message: 'I can assist you with that. Let us perform a soft power reset. Could you unplug the main power cord from the wall socket for 60 seconds?', timestamp: '00:52' },
      { id: 'th-4', speaker: 'customer', message: 'Alright, unplugged. Waiting... Okay, plugging it back in now.', timestamp: '01:45' },
      { id: 'th-5', speaker: 'ai', message: 'Now press and hold the power button on the TV remote for 5 seconds until you see the Sony logo.', timestamp: '02:05' },
      { id: 'th-6', speaker: 'customer', message: 'Oh excellent! The Sony logo just came up and the picture is back. Thank you!', timestamp: '02:30' },
      { id: 'th-7', speaker: 'ai', message: 'You are most welcome. The issue was an HDMI handshake timeout. I have logged this resolution in your profile. Have a wonderful evening!', timestamp: '02:42' },
    ],
    analysis: {
      intent: 'Product Issue',
      appliance: 'Television',
      issue: 'Video display freeze / black screen with normal audio',
      sentiment: 'Positive',
      priority: 'Medium',
      confidence: 96,
      summary: 'Guided customer through 60-second power cycle reset to resolve HDMI display handshake lockup on Sony Bravia 55X74L.',
    },
    actionsTaken: [
      { id: 'a1', action: 'CHECK_CUSTOMER', description: 'Customer identified: Amit Verma', completed: true, timestamp: '00:03' },
      { id: 'a2', action: 'CHECK_APPLIANCE', description: 'Identified Sony Bravia KD-55X74L', completed: true, timestamp: '00:27' },
      { id: 'a3', action: 'SEND_CONFIRMATION', description: 'Resolution recorded in customer history', completed: true, timestamp: '02:44' },
    ],
  },
  {
    id: 'CALL-83919',
    customerId: 'CUST-1005',
    customerName: 'Arjun Singh',
    customerPhone: '+91 97170 XXXXX',
    appliance: 'Refrigerator',
    applianceId: 'APP-2013',
    intent: 'Installation',
    issue: 'Demo and temperature setting guide for new refrigerator',
    duration: '02:10',
    durationSeconds: 130,
    sentiment: 'Positive',
    outcome: 'Resolved by AI',
    priority: 'Low',
    aiState: 'Completed',
    aiConfidence: 98,
    date: 'Today, 19:15',
    transcript: [
      { id: 'th-11', speaker: 'ai', message: 'Welcome to HomeCare support. How may I assist you today, Mr. Singh?', timestamp: '00:02' },
      { id: 'th-12', speaker: 'customer', message: 'Hi, I received my Samsung refrigerator yesterday. What is the recommended summer temperature setting?', timestamp: '00:22' },
      { id: 'th-13', speaker: 'ai', message: 'Congratulations on your new Samsung double door! For optimal cooling in current weather, set the fridge compartment to 3 degrees Celsius and the freezer to minus 19 degrees Celsius.', timestamp: '00:50' },
      { id: 'th-14', speaker: 'customer', message: 'Understood. Should I keep convertible mode on?', timestamp: '01:20' },
      { id: 'th-15', speaker: 'ai', message: 'Keep standard mode on unless you need extra fridge space. In that case, hold the Freezer Convert button for 3 seconds.', timestamp: '01:45' },
      { id: 'th-16', speaker: 'customer', message: 'Very clear, thanks a lot for the quick guide!', timestamp: '02:05' },
    ],
    analysis: {
      intent: 'Installation',
      appliance: 'Refrigerator',
      issue: 'Temperature optimization and convertible mode guidance',
      sentiment: 'Positive',
      priority: 'Low',
      confidence: 98,
      summary: 'Provided standard temperature guidelines (3°C / -19°C) and explained convertible mode controls for newly installed Samsung RT37C.',
    },
    actionsTaken: [
      { id: 'a11', action: 'CHECK_CUSTOMER', description: 'Customer identified: Arjun Singh', completed: true, timestamp: '00:03' },
      { id: 'a12', action: 'CHECK_APPLIANCE', description: 'Verified Samsung RT37C4512S8', completed: true, timestamp: '00:24' },
      { id: 'a13', action: 'SEND_CONFIRMATION', description: 'Sent quick settings SMS link to customer', completed: true, timestamp: '02:08' },
    ],
  },
  {
    id: 'CALL-83918',
    customerId: 'CUST-1007',
    customerName: 'Vikram Malhotra',
    customerPhone: '+91 98300 XXXXX',
    appliance: 'Air Conditioner',
    applianceId: 'APP-2017',
    intent: 'Warranty',
    issue: 'Annual comprehensive maintenance plan renewal',
    duration: '01:55',
    durationSeconds: 115,
    sentiment: 'Positive',
    outcome: 'Resolved by AI',
    priority: 'Low',
    aiState: 'Completed',
    aiConfidence: 95,
    date: 'Today, 18:40',
    transcript: [
      { id: 'th-21', speaker: 'ai', message: 'Welcome to HomeCare support. How can I help you today, Mr. Malhotra?', timestamp: '00:02' },
      { id: 'th-22', speaker: 'customer', message: 'Hello, I want to confirm the warranty expiry on my Mitsubishi 1.5 ton AC and check renewal options.', timestamp: '00:26' },
      { id: 'th-23', speaker: 'ai', message: 'Your Mitsubishi Heavy Duty AC is covered under standard comprehensive warranty until April 17, 2027. You have 7 months remaining before renewal is required.', timestamp: '00:54' },
      { id: 'th-24', speaker: 'customer', message: 'Oh perfect, I thought it ended this year. Thank you!', timestamp: '01:25' },
    ],
    analysis: {
      intent: 'Warranty',
      appliance: 'Air Conditioner',
      issue: 'Warranty status check and extension schedule inquiry',
      sentiment: 'Positive',
      priority: 'Low',
      confidence: 95,
      summary: 'Verified customer warranty dates and notified that standard cover continues active through April 2027.',
    },
    actionsTaken: [
      { id: 'a21', action: 'CHECK_CUSTOMER', description: 'Customer identified: Vikram Malhotra', completed: true, timestamp: '00:03' },
      { id: 'a22', action: 'CHECK_WARRANTY', description: 'Warranty validity checked: Active till Apr 2027', completed: true, timestamp: '00:30' },
    ],
  },
  {
    id: 'CALL-83917',
    customerId: 'CUST-1009',
    customerName: 'Rohan Deshmukh',
    customerPhone: '+91 98220 XXXXX',
    appliance: 'Television',
    applianceId: 'APP-2024',
    intent: 'Product Issue',
    issue: 'Wi-Fi disconnects frequently on OnePlus TV',
    duration: '03:15',
    durationSeconds: 195,
    sentiment: 'Neutral',
    outcome: 'Resolved by AI',
    priority: 'Medium',
    aiState: 'Completed',
    aiConfidence: 92,
    date: 'Today, 18:10',
    transcript: [
      { id: 'th-31', speaker: 'ai', message: 'Welcome to HomeCare. How can I assist you today, Mr. Deshmukh?', timestamp: '00:02' },
      { id: 'th-32', speaker: 'customer', message: 'My OnePlus 50 inch TV drops Wi-Fi connection every 15 minutes during streaming.', timestamp: '00:28' },
      { id: 'th-33', speaker: 'ai', message: 'Let us change the network band settings. Go to Settings > Network & Internet > Select your 5GHz Wi-Fi and toggle off IP auto-sleep.', timestamp: '01:05' },
      { id: 'th-34', speaker: 'customer', message: 'Done that. It reconnected and says signal strength Excellent.', timestamp: '02:20' },
      { id: 'th-35', speaker: 'ai', message: 'Great! Also please ensure Date & Time is set to "Use network-provided time" so authentication certificates do not expire.', timestamp: '02:40' },
    ],
    analysis: {
      intent: 'Product Issue',
      appliance: 'Television',
      issue: 'Intermittent Wi-Fi DHCP drop on Android TV OS',
      sentiment: 'Neutral',
      priority: 'Medium',
      confidence: 92,
      summary: 'Assisted customer in updating network lease settings and time synchronization to fix Wi-Fi dropouts.',
    },
    actionsTaken: [
      { id: 'a31', action: 'CHECK_CUSTOMER', description: 'Customer identified: Rohan Deshmukh', completed: true, timestamp: '00:04' },
      { id: 'a32', action: 'CHECK_APPLIANCE', description: 'Appliance identified: OnePlus 50 Y1S Pro', completed: true, timestamp: '00:32' },
    ],
  },
  {
    id: 'CALL-83916',
    customerId: 'CUST-1011',
    customerName: 'Manoj Kumar',
    customerPhone: '+91 98188 XXXXX',
    appliance: 'Washing Machine',
    applianceId: 'APP-2030',
    intent: 'Product Issue',
    issue: 'Burning smell and motor stopped',
    duration: '02:30',
    durationSeconds: 150,
    sentiment: 'Frustrated',
    outcome: 'Service Request Created',
    priority: 'Critical',
    aiState: 'Completed',
    aiConfidence: 97,
    date: 'Today, 17:35',
    transcript: [
      { id: 'th-41', speaker: 'ai', message: 'Welcome to HomeCare support. How can I help you today?', timestamp: '00:02' },
      { id: 'th-42', speaker: 'customer', message: 'There is a burning plastic smell coming from my washing machine and the drum suddenly halted!', timestamp: '00:24' },
      { id: 'th-43', speaker: 'ai', message: 'Mr. Kumar, please immediately turn off the main switch and unplug the appliance from the wall. Do not attempt to open the lid.', timestamp: '00:46' },
      { id: 'th-44', speaker: 'customer', message: 'I turned it off right away. Is there a fire hazard?', timestamp: '01:10' },
      { id: 'th-45', speaker: 'ai', message: 'Keeping it unplugged eliminates electrical danger. I have logged a Critical Service Request SR-10479. A senior technician has been scheduled for priority morning dispatch.', timestamp: '01:45' },
    ],
    analysis: {
      intent: 'Product Issue',
      appliance: 'Washing Machine',
      issue: 'Electrical burning smell / belt-motor failure',
      sentiment: 'Frustrated',
      priority: 'Critical',
      confidence: 97,
      summary: 'Emergency electrical burning odor. Instructed safety disconnect and booked critical emergency technician ticket SR-10479.',
    },
    actionsTaken: [
      { id: 'a41', action: 'CHECK_CUSTOMER', description: 'Identified Manoj Kumar', completed: true, timestamp: '00:03' },
      { id: 'a42', action: 'CHECK_APPLIANCE', description: 'Whirlpool Stainwash Ultra (APP-2030)', completed: true, timestamp: '00:26' },
      { id: 'a43', action: 'CREATE_SERVICE_REQUEST', description: 'Created Critical Request SR-10479', completed: true, timestamp: '01:50' },
      { id: 'a44', action: 'SEND_CONFIRMATION', description: 'Safety guidance SMS and ticket confirmation dispatched', completed: true, timestamp: '02:25' },
    ],
  },
  {
    id: 'CALL-83915',
    customerId: 'CUST-1012',
    customerName: 'Divya Nair',
    customerPhone: '+91 98470 XXXXX',
    appliance: 'Refrigerator',
    applianceId: 'APP-2031',
    intent: 'Product Issue',
    issue: 'Excessive frost buildup on freezer walls',
    duration: '02:05',
    durationSeconds: 125,
    sentiment: 'Neutral',
    outcome: 'Service Request Created',
    priority: 'Medium',
    aiState: 'Completed',
    aiConfidence: 93,
    date: 'Today, 17:02',
    transcript: [
      { id: 'th-51', speaker: 'ai', message: 'Welcome to HomeCare. How may I assist you today, Ms. Nair?', timestamp: '00:02' },
      { id: 'th-52', speaker: 'customer', message: 'My LG frost-free refrigerator has thick ice forming in the freezer compartment.', timestamp: '00:26' },
      { id: 'th-53', speaker: 'ai', message: 'In a frost-free unit, thick ice buildup typically indicates a defrost timer or thermal bimetal fuse malfunction. Is the door gasket sealing tight all around?', timestamp: '00:55' },
      { id: 'th-54', speaker: 'customer', message: 'Yes, the rubber seal looks fine. The fan sounds like it is struggling behind the ice.', timestamp: '01:25' },
      { id: 'th-55', speaker: 'ai', message: 'Thank you. I have registered service request SR-10478 for a defrost heater check under your active LG warranty.', timestamp: '01:52' },
    ],
    analysis: {
      intent: 'Product Issue',
      appliance: 'Refrigerator',
      issue: 'Defrost cycle failure / ice buildup in frost-free unit',
      sentiment: 'Neutral',
      priority: 'Medium',
      confidence: 93,
      summary: 'Diagnosed failure of automatic defrost heater or sensor in LG GL-S292. Created ticket SR-10478.',
    },
    actionsTaken: [
      { id: 'a51', action: 'CHECK_CUSTOMER', description: 'Customer identified: Divya Nair', completed: true, timestamp: '00:03' },
      { id: 'a52', action: 'CREATE_SERVICE_REQUEST', description: 'Created SR-10478', completed: true, timestamp: '01:54' },
    ],
  },
  {
    id: 'CALL-83914',
    customerId: 'CUST-1014',
    customerName: 'Pooja Agarwal',
    customerPhone: '+91 98390 XXXXX',
    appliance: 'Water Purifier',
    applianceId: 'APP-2032',
    intent: 'Product Issue',
    issue: 'Beeping alarm on Kent RO water purifier',
    duration: '01:48',
    durationSeconds: 108,
    sentiment: 'Neutral',
    outcome: 'Service Request Created',
    priority: 'Medium',
    aiState: 'Completed',
    aiConfidence: 96,
    date: 'Today, 16:20',
    transcript: [
      { id: 'th-61', speaker: 'ai', message: 'Hello, welcome to HomeCare. How may I assist you today, Ms. Agarwal?', timestamp: '00:02' },
      { id: 'th-62', speaker: 'customer', message: 'Hi, my Kent RO is beeping continuously with 2 beeps every few seconds.', timestamp: '00:22' },
      { id: 'th-63', speaker: 'ai', message: 'Two beeps every 2 seconds on your Kent Supreme indicates a UV Fail alarm, meaning the UV disinfection lamp needs inspection or replacement.', timestamp: '00:50' },
      { id: 'th-64', speaker: 'customer', message: 'Is the water still safe to drink right now?', timestamp: '01:10' },
      { id: 'th-65', speaker: 'ai', message: 'We recommend boiling the dispensed water until the UV lamp is replaced. I have created service request SR-10477 with a technician visit booked for tomorrow.', timestamp: '01:35' },
    ],
    analysis: {
      intent: 'Product Issue',
      appliance: 'Water Purifier',
      issue: 'Kent RO UV Lamp fail alarm (2 beeps frequency)',
      sentiment: 'Neutral',
      priority: 'Medium',
      confidence: 96,
      summary: 'Accurately recognized Kent UV fail alarm acoustic signal. Provided water safety advisory and generated SR-10477.',
    },
    actionsTaken: [
      { id: 'a61', action: 'CHECK_CUSTOMER', description: 'Customer identified: Pooja Agarwal', completed: true, timestamp: '00:03' },
      { id: 'a62', action: 'CREATE_SERVICE_REQUEST', description: 'Created SR-10477', completed: true, timestamp: '01:38' },
    ],
  },
  {
    id: 'CALL-83913',
    customerId: 'CUST-1013',
    customerName: 'Suresh Joshi',
    customerPhone: '+91 98290 XXXXX',
    appliance: 'Air Conditioner',
    applianceId: 'APP-2002',
    intent: 'Order Status',
    issue: 'Tracking technician arrival time for scheduled maintenance',
    duration: '01:15',
    durationSeconds: 75,
    sentiment: 'Positive',
    outcome: 'Resolved by AI',
    priority: 'Low',
    aiState: 'Completed',
    aiConfidence: 99,
    date: 'Today, 15:45',
    transcript: [
      { id: 'th-71', speaker: 'ai', message: 'Welcome to HomeCare support. How can I help you today, Mr. Joshi?', timestamp: '00:02' },
      { id: 'th-72', speaker: 'customer', message: 'Hello, I had a technician visit scheduled today between 3 PM and 5 PM for my AC. What is the current status?', timestamp: '00:25' },
      { id: 'th-73', speaker: 'ai', message: 'Your service request SR-10470 is assigned to technician Ramesh Kumar. He is currently 15 minutes away and will arrive by 4:10 PM. His direct contact is shared via SMS.', timestamp: '00:52' },
      { id: 'th-74', speaker: 'customer', message: 'Great, thanks for the exact update!', timestamp: '01:08' },
    ],
    analysis: {
      intent: 'Order Status',
      appliance: 'Air Conditioner',
      issue: 'Real-time technician ETA inquiry',
      sentiment: 'Positive',
      priority: 'Low',
      confidence: 99,
      summary: 'Retrieved assigned technician GPS status and delivered arrival window without needing support rep transfer.',
    },
    actionsTaken: [
      { id: 'a71', action: 'CHECK_CUSTOMER', description: 'Customer identified: Suresh Joshi', completed: true, timestamp: '00:03' },
      { id: 'a72', action: 'CHECK_REQUEST_STATUS', description: 'Retrieved status for SR-10470 (In Route)', completed: true, timestamp: '00:35' },
    ],
  },
  {
    id: 'CALL-83912',
    customerId: 'CUST-1016',
    customerName: 'Meera Nambiar',
    customerPhone: '+91 98460 XXXXX',
    appliance: 'Washing Machine',
    applianceId: 'APP-2001',
    intent: 'Human Agent',
    issue: 'Repeated breakdown of washing machine after two visits',
    duration: '04:10',
    durationSeconds: 250,
    sentiment: 'Frustrated',
    outcome: 'Human Escalation',
    priority: 'High',
    aiState: 'Completed',
    aiConfidence: 81,
    date: 'Today, 15:10',
    transcript: [
      { id: 'th-81', speaker: 'ai', message: 'Welcome to HomeCare. How may I assist you today, Ms. Nambiar?', timestamp: '00:02' },
      { id: 'th-82', speaker: 'customer', message: 'I am extremely unhappy. A technician came twice this week to fix my washing machine and it broke down again within 2 hours of him leaving. I want to speak to your service head right now.', timestamp: '00:30' },
      { id: 'th-83', speaker: 'ai', message: 'I sincerely apologize for the frustration this has caused, Ms. Nambiar. Having a machine break down immediately after two visits is unacceptable. I am transferring your call directly to our Senior Quality Escalation Manager.', timestamp: '01:05' },
    ],
    analysis: {
      intent: 'Human Agent',
      appliance: 'Washing Machine',
      issue: 'Repeat failure within 48 hours of dual service visits',
      sentiment: 'Frustrated',
      priority: 'High',
      confidence: 81,
      summary: 'Repeat failure trigger detected. Automatically routed to Level 2 escalation supervisor.',
    },
    actionsTaken: [
      { id: 'a81', action: 'CHECK_CUSTOMER', description: 'Identified Meera Nambiar (VIP Tier)', completed: true, timestamp: '00:03' },
      { id: 'a82', action: 'CHECK_SERVICE_HISTORY', description: 'Detected 2 service attempts in past 5 days', completed: true, timestamp: '00:35' },
      { id: 'a83', action: 'ESCALATE_HUMAN', description: 'Transferred directly to Quality Escalation Manager', completed: true, timestamp: '01:10' },
    ],
  },
  {
    id: 'CALL-83911',
    customerId: 'CUST-1017',
    customerName: 'Alok Saxena',
    customerPhone: '+91 98111 XXXXX',
    appliance: 'Air Conditioner',
    applianceId: 'APP-2009',
    intent: 'Installation',
    issue: 'Request for AC uninstallation and re-installation at new apartment',
    duration: '02:22',
    durationSeconds: 142,
    sentiment: 'Neutral',
    outcome: 'Service Request Created',
    priority: 'Low',
    aiState: 'Completed',
    aiConfidence: 94,
    date: 'Today, 14:30',
    transcript: [
      { id: 'th-91', speaker: 'ai', message: 'Welcome to HomeCare support. How can I help you today?', timestamp: '00:02' },
      { id: 'th-92', speaker: 'customer', message: 'I am moving homes next Saturday and need my split AC uninstalled and reinstalled at the new address.', timestamp: '00:26' },
      { id: 'th-93', speaker: 'ai', message: 'Certainly! I can schedule our relocation service. The standard rate covers uninstallation, copper pipe vacuuming, and bracket mounting at the new location.', timestamp: '00:58' },
      { id: 'th-94', speaker: 'customer', message: 'That sounds perfect. Book it for next Saturday 10 AM.', timestamp: '01:25' },
    ],
    analysis: {
      intent: 'Installation',
      appliance: 'Air Conditioner',
      issue: 'Relocation uninstallation and re-mounting request',
      sentiment: 'Neutral',
      priority: 'Low',
      confidence: 94,
      summary: 'Scheduled AC shifting and installation package for upcoming weekend.',
    },
    actionsTaken: [
      { id: 'a91', action: 'CHECK_CUSTOMER', description: 'Customer identified: Alok Saxena', completed: true, timestamp: '00:03' },
      { id: 'a92', action: 'CREATE_SERVICE_REQUEST', description: 'Created SR-10468 (Installation Relocation)', completed: true, timestamp: '01:30' },
    ],
  },
  {
    id: 'CALL-83910',
    customerId: 'CUST-1018',
    customerName: 'Shreya Chatterjee',
    customerPhone: '+91 98310 XXXXX',
    appliance: 'Refrigerator',
    applianceId: 'APP-2019',
    intent: 'Product Issue',
    issue: 'Water leaking underneath refrigerator',
    duration: '02:08',
    durationSeconds: 128,
    sentiment: 'Neutral',
    outcome: 'Resolved by AI',
    priority: 'Low',
    aiState: 'Completed',
    aiConfidence: 95,
    date: 'Today, 13:50',
    transcript: [
      { id: 'th-101', speaker: 'ai', message: 'Welcome to HomeCare. How can I assist you today, Ms. Chatterjee?', timestamp: '00:02' },
      { id: 'th-102', speaker: 'customer', message: 'There is a small puddle of clear water forming beneath my refrigerator on the floor.', timestamp: '00:25' },
      { id: 'th-103', speaker: 'ai', message: 'This frequently occurs when the condensation drain pan at the back becomes misaligned or full after high humidity days. Can you check if the plastic tray above the compressor is sitting level?', timestamp: '00:54' },
      { id: 'th-104', speaker: 'customer', message: 'Let me look behind with a flashlight... Yes! The black plastic tray was tilted and dripping on the floor. I snapped it back into place.', timestamp: '01:38' },
      { id: 'th-105', speaker: 'ai', message: 'Splendid! Once aligned, the compressor heat will naturally evaporate normal condensation. If it overflows again, let us know!', timestamp: '01:58' },
    ],
    analysis: {
      intent: 'Product Issue',
      appliance: 'Refrigerator',
      issue: 'Evaporator drip tray misaligned causing puddle',
      sentiment: 'Positive',
      priority: 'Low',
      confidence: 95,
      summary: 'Guided customer to locate and reseat the rear condensation tray, preventing unnecessary service dispatch.',
    },
    actionsTaken: [
      { id: 'a101', action: 'CHECK_CUSTOMER', description: 'Customer identified: Shreya Chatterjee', completed: true, timestamp: '00:03' },
      { id: 'a102', action: 'SEND_CONFIRMATION', description: 'Logged self-resolution in profile', completed: true, timestamp: '02:02' },
    ],
  },
  {
    id: 'CALL-83909',
    customerId: 'CUST-1019',
    customerName: 'Gaurav Bhatia',
    customerPhone: '+91 98720 XXXXX',
    appliance: 'Water Purifier',
    applianceId: 'APP-2005',
    intent: 'Product Issue',
    issue: 'Water flow rate from RO faucet is extremely slow',
    duration: '02:40',
    durationSeconds: 160,
    sentiment: 'Neutral',
    outcome: 'Service Request Created',
    priority: 'Medium',
    aiState: 'Completed',
    aiConfidence: 93,
    date: 'Today, 13:15',
    transcript: [
      { id: 'th-111', speaker: 'ai', message: 'Welcome to HomeCare. How may I assist you today, Mr. Bhatia?', timestamp: '00:02' },
      { id: 'th-112', speaker: 'customer', message: 'My water purifier is taking nearly 30 minutes to fill one bottle. The stream is very thin.', timestamp: '00:26' },
      { id: 'th-113', speaker: 'ai', message: 'A low flow rate usually signals clogged pre-carbon or RO membrane filters, especially if inlet water pressure is normal. How long ago was the external pre-filter changed?', timestamp: '00:55' },
      { id: 'th-114', speaker: 'customer', message: 'It has been more than 10 months now.', timestamp: '01:20' },
      { id: 'th-115', speaker: 'ai', message: 'Understood. A filter replacement kit is required. I have generated service ticket SR-10465 for our water purifier specialist to visit with the genuine filter set.', timestamp: '01:50' },
    ],
    analysis: {
      intent: 'Product Issue',
      appliance: 'Water Purifier',
      issue: 'Clogged RO membrane / low flow rate',
      sentiment: 'Neutral',
      priority: 'Medium',
      confidence: 93,
      summary: 'Diagnosed filter saturation after 10 months of use. Booked technician visit with replacement parts.',
    },
    actionsTaken: [
      { id: 'a111', action: 'CHECK_CUSTOMER', description: 'Customer identified: Gaurav Bhatia', completed: true, timestamp: '00:03' },
      { id: 'a112', action: 'CREATE_SERVICE_REQUEST', description: 'Created SR-10465', completed: true, timestamp: '02:00' },
    ],
  },
  {
    id: 'CALL-83908',
    customerId: 'CUST-1020',
    customerName: 'Ritu Sen',
    customerPhone: '+91 98305 XXXXX',
    appliance: 'Air Conditioner',
    applianceId: 'APP-2004',
    intent: 'Product Issue',
    issue: 'AC unit making rattling sound from blower fan',
    duration: '02:15',
    durationSeconds: 135,
    sentiment: 'Neutral',
    outcome: 'Service Request Created',
    priority: 'Medium',
    aiState: 'Completed',
    aiConfidence: 94,
    date: 'Today, 12:40',
    transcript: [
      { id: 'th-121', speaker: 'ai', message: 'Welcome to HomeCare support. How can I help you today?', timestamp: '00:02' },
      { id: 'th-122', speaker: 'customer', message: 'Whenever I turn on the AC, there is a rhythmic rattling sound from inside the vent.', timestamp: '00:24' },
      { id: 'th-123', speaker: 'ai', message: 'Does the noise increase in speed when you increase the fan speed on the remote?', timestamp: '00:48' },
      { id: 'th-124', speaker: 'customer', message: 'Yes! It rattles much faster on High fan mode.', timestamp: '01:10' },
      { id: 'th-125', speaker: 'ai', message: 'That confirms a loose blower wheel or debris in the fan barrel. I have scheduled an inspection under ticket SR-10463.', timestamp: '01:38' },
    ],
    analysis: {
      intent: 'Product Issue',
      appliance: 'Air Conditioner',
      issue: 'Blower fan blade obstruction / mechanical rattle',
      sentiment: 'Neutral',
      priority: 'Medium',
      confidence: 94,
      summary: 'Correlated rattling frequency with fan RPM. Scheduled blower assembly inspection.',
    },
    actionsTaken: [
      { id: 'a121', action: 'CHECK_CUSTOMER', description: 'Customer identified: Ritu Sen', completed: true, timestamp: '00:03' },
      { id: 'a122', action: 'CREATE_SERVICE_REQUEST', description: 'Created SR-10463', completed: true, timestamp: '01:42' },
    ],
  },
  {
    id: 'CALL-83907',
    customerId: 'CUST-1021',
    customerName: 'Deepak Choudhary',
    customerPhone: '+91 98292 XXXXX',
    appliance: 'Television',
    applianceId: 'APP-2006',
    intent: 'Warranty',
    issue: 'Extended warranty plan pricing and coverage details',
    duration: '01:40',
    durationSeconds: 100,
    sentiment: 'Positive',
    outcome: 'Resolved by AI',
    priority: 'Low',
    aiState: 'Completed',
    aiConfidence: 97,
    date: 'Today, 12:05',
    transcript: [
      { id: 'th-131', speaker: 'ai', message: 'Welcome to HomeCare. How may I assist you today, Mr. Choudhary?', timestamp: '00:02' },
      { id: 'th-132', speaker: 'customer', message: 'I bought my smart TV 10 months ago. Can I still purchase the 2-year extended warranty plan?', timestamp: '00:25' },
      { id: 'th-133', speaker: 'ai', message: 'Yes, extended warranty can be purchased any time before the 1-year manufacturer warranty concludes. The 2-year comprehensive extension is ₹2,499 including panel protection. Would you like the secure payment link via SMS?', timestamp: '00:55' },
      { id: 'th-134', speaker: 'customer', message: 'Yes please send the link to this phone number.', timestamp: '01:18' },
    ],
    analysis: {
      intent: 'Warranty',
      appliance: 'Television',
      issue: 'Extended panel warranty qualification and quotation',
      sentiment: 'Positive',
      priority: 'Low',
      confidence: 97,
      summary: 'Verified appliance age within 365-day eligibility. Dispatched official payment and policy link.',
    },
    actionsTaken: [
      { id: 'a131', action: 'CHECK_CUSTOMER', description: 'Customer identified: Deepak Choudhary', completed: true, timestamp: '00:03' },
      { id: 'a132', action: 'SEND_CONFIRMATION', description: 'Dispatched warranty purchase link', completed: true, timestamp: '01:25' },
    ],
  },
  {
    id: 'CALL-83906',
    customerId: 'CUST-1022',
    customerName: 'Tarun Sengupta',
    customerPhone: '+91 98205 XXXXX',
    appliance: 'Washing Machine',
    applianceId: 'APP-2001',
    intent: 'Product Issue',
    issue: 'Washing machine door stuck locked after cycle finished',
    duration: '02:00',
    durationSeconds: 120,
    sentiment: 'Neutral',
    outcome: 'Resolved by AI',
    priority: 'Medium',
    aiState: 'Completed',
    aiConfidence: 95,
    date: 'Today, 11:30',
    transcript: [
      { id: 'th-141', speaker: 'ai', message: 'Welcome to HomeCare. How can I help you today, Mr. Sengupta?', timestamp: '00:02' },
      { id: 'th-142', speaker: 'customer', message: 'My front load washing machine finished 10 minutes ago, but the door lock will not release.', timestamp: '00:24' },
      { id: 'th-143', speaker: 'ai', message: 'For safety, front load doors lock if water remains or temperature is high. Try unplugging the machine for 3 minutes to reset the bi-metal latch.', timestamp: '00:52' },
      { id: 'th-144', speaker: 'customer', message: 'Okay, I waited 3 minutes... Click! Yes, the door unlocked. Thank you!', timestamp: '01:40' },
    ],
    analysis: {
      intent: 'Product Issue',
      appliance: 'Washing Machine',
      issue: 'Thermal safety interlock delay on front load door',
      sentiment: 'Positive',
      priority: 'Medium',
      confidence: 95,
      summary: 'Explained thermal door lock release mechanism and resolved lockup without tool usage.',
    },
    actionsTaken: [
      { id: 'a141', action: 'CHECK_CUSTOMER', description: 'Customer identified: Tarun Sengupta', completed: true, timestamp: '00:03' },
      { id: 'a142', action: 'SEND_CONFIRMATION', description: 'Logged self-resolution in history', completed: true, timestamp: '01:48' },
    ],
  },
  {
    id: 'CALL-83905',
    customerId: 'CUST-1001',
    customerName: 'Rahul Sharma',
    customerPhone: '+91 98201 XXXXX',
    appliance: 'Air Conditioner',
    applianceId: 'APP-2002',
    intent: 'Product Issue',
    issue: 'Air conditioner remote control unresponsive',
    duration: '01:30',
    durationSeconds: 90,
    sentiment: 'Neutral',
    outcome: 'Resolved by AI',
    priority: 'Low',
    aiState: 'Completed',
    aiConfidence: 96,
    date: 'Yesterday, 18:20',
    transcript: [
      { id: 'th-151', speaker: 'ai', message: 'Welcome to HomeCare. How can I assist you today, Mr. Sharma?', timestamp: '00:02' },
      { id: 'th-152', speaker: 'customer', message: 'My LG AC remote is not working even though I put in fresh batteries.', timestamp: '00:22' },
      { id: 'th-153', speaker: 'ai', message: 'Let us check the IR transmitter. Look at the front tip of the remote through your smartphone camera while pressing any button. Do you see a purple or pink blinking light in the screen?', timestamp: '00:48' },
      { id: 'th-154', speaker: 'customer', message: 'Let me try that... Ah, no light at all. One battery terminal was inverted! Fixed it and now the AC turned right on. Neat trick!', timestamp: '01:15' },
    ],
    analysis: {
      intent: 'Product Issue',
      appliance: 'Air Conditioner',
      issue: 'Remote battery contact / IR transmitter diagnosis',
      sentiment: 'Positive',
      priority: 'Low',
      confidence: 96,
      summary: 'Used phone camera IR diagnostic technique to assist customer with remote control issue.',
    },
    actionsTaken: [
      { id: 'a151', action: 'CHECK_CUSTOMER', description: 'Customer identified: Rahul Sharma', completed: true, timestamp: '00:03' },
    ],
  },
  {
    id: 'CALL-83904',
    customerId: 'CUST-1002',
    customerName: 'Priya Mehta',
    customerPhone: '+91 98114 XXXXX',
    appliance: 'Water Purifier',
    applianceId: 'APP-2005',
    intent: 'Warranty',
    issue: 'Annual maintenance service coupon confirmation',
    duration: '01:18',
    durationSeconds: 78,
    sentiment: 'Positive',
    outcome: 'Resolved by AI',
    priority: 'Low',
    aiState: 'Completed',
    aiConfidence: 98,
    date: 'Yesterday, 16:50',
    transcript: [
      { id: 'th-161', speaker: 'ai', message: 'Welcome to HomeCare. How can I help you today, Ms. Mehta?', timestamp: '00:02' },
      { id: 'th-162', speaker: 'customer', message: 'I received a message about an annual service coupon for my Kent RO. How do I redeem it?', timestamp: '00:24' },
      { id: 'th-163', speaker: 'ai', message: 'Your coupon is already automatically registered to your profile! When the technician arrives for scheduled service, share OTP 4920 to apply 100% discount on labor.', timestamp: '00:52' },
      { id: 'th-164', speaker: 'customer', message: 'Wonderful, thank you so much!', timestamp: '01:10' },
    ],
    analysis: {
      intent: 'Warranty',
      appliance: 'Water Purifier',
      issue: 'Service coupon OTP redemption instructions',
      sentiment: 'Positive',
      priority: 'Low',
      confidence: 98,
      summary: 'Provided service OTP and verified coupon validity.',
    },
    actionsTaken: [
      { id: 'a161', action: 'CHECK_CUSTOMER', description: 'Identified Priya Mehta', completed: true, timestamp: '00:03' },
    ],
  },
  {
    id: 'CALL-83903',
    customerId: 'CUST-1003',
    customerName: 'Amit Verma',
    customerPhone: '+91 98450 XXXXX',
    appliance: 'Washing Machine',
    applianceId: 'APP-2007',
    intent: 'Product Issue',
    issue: 'Lint accumulation on dark clothes',
    duration: '02:05',
    durationSeconds: 125,
    sentiment: 'Neutral',
    outcome: 'Resolved by AI',
    priority: 'Low',
    aiState: 'Completed',
    aiConfidence: 94,
    date: 'Yesterday, 14:10',
    transcript: [
      { id: 'th-171', speaker: 'ai', message: 'Welcome to HomeCare. How may I assist you today, Mr. Verma?', timestamp: '00:02' },
      { id: 'th-172', speaker: 'customer', message: 'My IFB washing machine is leaving white lint all over black trousers.', timestamp: '00:25' },
      { id: 'th-173', speaker: 'ai', message: 'This typically happens when the internal magic lint filter is full or during tub sediment buildup. Run a Tub Clean cycle at 60 degrees with descaling powder, and clean the removable mesh filter located inside the drum.', timestamp: '00:58' },
      { id: 'th-174', speaker: 'customer', message: 'I have never cleaned that mesh filter. I will do that right now.', timestamp: '01:30' },
    ],
    analysis: {
      intent: 'Product Issue',
      appliance: 'Washing Machine',
      issue: 'Lint filter cleaning maintenance advice',
      sentiment: 'Neutral',
      priority: 'Low',
      confidence: 94,
      summary: 'Explained tub cleaning maintenance procedure and lint filter removal.',
    },
    actionsTaken: [
      { id: 'a171', action: 'CHECK_CUSTOMER', description: 'Customer identified: Amit Verma', completed: true, timestamp: '00:03' },
    ],
  },
  {
    id: 'CALL-83902',
    customerId: 'CUST-1004',
    customerName: 'Neha Kapoor',
    customerPhone: '+91 98102 XXXXX',
    appliance: 'Television',
    applianceId: 'APP-2012',
    intent: 'Installation',
    issue: 'Wall mount bracket re-tightening request',
    duration: '01:50',
    durationSeconds: 110,
    sentiment: 'Neutral',
    outcome: 'Service Request Created',
    priority: 'Medium',
    aiState: 'Completed',
    aiConfidence: 96,
    date: 'Yesterday, 11:20',
    transcript: [
      { id: 'th-181', speaker: 'ai', message: 'Welcome to HomeCare VIP support. How can I help you today, Ms. Kapoor?', timestamp: '00:02' },
      { id: 'th-182', speaker: 'customer', message: 'The swivel wall mount for my 65 inch Samsung TV feels slightly loose when tilting.', timestamp: '00:25' },
      { id: 'th-183', speaker: 'ai', message: 'For safety of your 65 inch TV, please avoid tilting the unit until inspected. I have logged service ticket SR-10459 for our wall-mount specialist to anchor the bracket.', timestamp: '00:54' },
      { id: 'th-184', speaker: 'customer', message: 'Thanks, please send someone tomorrow.', timestamp: '01:20' },
    ],
    analysis: {
      intent: 'Installation',
      appliance: 'Television',
      issue: 'Heavy display wall mount bracket stability inspection',
      sentiment: 'Neutral',
      priority: 'Medium',
      confidence: 96,
      summary: 'Booked bracket inspection service request SR-10459 with safety precautionary advice.',
    },
    actionsTaken: [
      { id: 'a181', action: 'CHECK_CUSTOMER', description: 'Customer identified: Neha Kapoor', completed: true, timestamp: '00:03' },
      { id: 'a182', action: 'CREATE_SERVICE_REQUEST', description: 'Created SR-10459', completed: true, timestamp: '01:00' },
    ],
  },
  {
    id: 'CALL-83901',
    customerId: 'CUST-1005',
    customerName: 'Arjun Singh',
    customerPhone: '+91 97170 XXXXX',
    appliance: 'Air Conditioner',
    applianceId: 'APP-2014',
    intent: 'Product Issue',
    issue: 'Window AC compressor cycling on and off every 2 minutes',
    duration: '02:30',
    durationSeconds: 150,
    sentiment: 'Frustrated',
    outcome: 'Service Request Created',
    priority: 'High',
    aiState: 'Completed',
    aiConfidence: 91,
    date: '2 days ago',
    transcript: [
      { id: 'th-191', speaker: 'ai', message: 'Welcome to HomeCare support. How may I assist you today, Mr. Singh?', timestamp: '00:02' },
      { id: 'th-192', speaker: 'customer', message: 'My window AC is short cycling. The compressor kicks on for two minutes and shuts off, room remains humid.', timestamp: '00:26' },
      { id: 'th-193', speaker: 'ai', message: 'Short cycling in window units is frequently caused by a frosted evaporator sensor or clogged condenser fins at the back. I have created service request SR-10455 for coil pressure testing.', timestamp: '00:58' },
    ],
    analysis: {
      intent: 'Product Issue',
      appliance: 'Air Conditioner',
      issue: 'Compressor thermal overload / short cycling',
      sentiment: 'Frustrated',
      priority: 'High',
      confidence: 91,
      summary: 'Diagnosed compressor short cycling. Booked service request SR-10455.',
    },
    actionsTaken: [
      { id: 'a191', action: 'CHECK_CUSTOMER', description: 'Customer identified: Arjun Singh', completed: true, timestamp: '00:03' },
      { id: 'a192', action: 'CREATE_SERVICE_REQUEST', description: 'Created SR-10455', completed: true, timestamp: '01:10' },
    ],
  },
  {
    id: 'CALL-83900',
    customerId: 'CUST-1006',
    customerName: 'Sneha Patel',
    customerPhone: '+91 98250 XXXXX',
    appliance: 'Water Purifier',
    applianceId: 'APP-2016',
    intent: 'Product Issue',
    issue: 'Taste of purified water is slightly metallic',
    duration: '02:12',
    durationSeconds: 132,
    sentiment: 'Neutral',
    outcome: 'Service Request Created',
    priority: 'Medium',
    aiState: 'Completed',
    aiConfidence: 93,
    date: '2 days ago',
    transcript: [
      { id: 'th-201', speaker: 'ai', message: 'Welcome to HomeCare. How may I assist you today, Ms. Patel?', timestamp: '00:02' },
      { id: 'th-202', speaker: 'customer', message: 'The water from my RO purifier has had a faint metallic aftertaste since yesterday.', timestamp: '00:26' },
      { id: 'th-203', speaker: 'ai', message: 'An altered taste typically points to post-carbon polisher saturation or low mineralizer levels. A technician with a calibrated TDS meter should evaluate the output. I am raising ticket SR-10452.', timestamp: '00:58' },
    ],
    analysis: {
      intent: 'Product Issue',
      appliance: 'Water Purifier',
      issue: 'TDS imbalance / post-carbon filter exhaustion',
      sentiment: 'Neutral',
      priority: 'Medium',
      confidence: 93,
      summary: 'Scheduled TDS assessment and carbon polisher replacement SR-10452.',
    },
    actionsTaken: [
      { id: 'a201', action: 'CHECK_CUSTOMER', description: 'Identified Sneha Patel', completed: true, timestamp: '00:03' },
      { id: 'a202', action: 'CREATE_SERVICE_REQUEST', description: 'Created SR-10452', completed: true, timestamp: '01:05' },
    ],
  },
  {
    id: 'CALL-83899',
    customerId: 'CUST-1007',
    customerName: 'Vikram Malhotra',
    customerPhone: '+91 98300 XXXXX',
    appliance: 'Television',
    applianceId: 'APP-2018',
    intent: 'Product Issue',
    issue: 'Dolby Atmos eARC soundbar audio sync delay',
    duration: '03:00',
    durationSeconds: 180,
    sentiment: 'Neutral',
    outcome: 'Resolved by AI',
    priority: 'Low',
    aiState: 'Completed',
    aiConfidence: 95,
    date: '3 days ago',
    transcript: [
      { id: 'th-211', speaker: 'ai', message: 'Welcome to HomeCare. How can I assist you today, Mr. Malhotra?', timestamp: '00:02' },
      { id: 'th-212', speaker: 'customer', message: 'Audio through HDMI eARC to my external receiver has a 200 millisecond lip sync lag on 4K movies.', timestamp: '00:28' },
      { id: 'th-213', speaker: 'ai', message: 'On LG OLED TVs, navigate to Sound > Advanced Settings > Match Screen and Sound > set to Bypass and toggle Digital Sound Output to Pass Through.', timestamp: '01:02' },
      { id: 'th-214', speaker: 'customer', message: 'Changing to Pass Through instantly fixed the lag! Perfect sync now.', timestamp: '02:15' },
    ],
    analysis: {
      intent: 'Product Issue',
      appliance: 'Television',
      issue: 'HDMI eARC audio latency / pass-through config',
      sentiment: 'Positive',
      priority: 'Low',
      confidence: 95,
      summary: 'Guided customer to configure digital audio pass-through bypass on LG OLED C3.',
    },
    actionsTaken: [
      { id: 'a211', action: 'CHECK_CUSTOMER', description: 'Customer identified: Vikram Malhotra', completed: true, timestamp: '00:03' },
    ],
  },
  {
    id: 'CALL-83898',
    customerId: 'CUST-1008',
    customerName: 'Ananya Iyer',
    customerPhone: '+91 98401 XXXXX',
    appliance: 'Washing Machine',
    applianceId: 'APP-2020',
    intent: 'Product Issue',
    issue: 'Child lock feature stuck enabled',
    duration: '01:30',
    durationSeconds: 90,
    sentiment: 'Neutral',
    outcome: 'Resolved by AI',
    priority: 'Low',
    aiState: 'Completed',
    aiConfidence: 97,
    date: '3 days ago',
    transcript: [
      { id: 'th-221', speaker: 'ai', message: 'Welcome to HomeCare. How can I help you today, Ms. Iyer?', timestamp: '00:02' },
      { id: 'th-222', speaker: 'customer', message: 'A key icon is blinking on my LG washing machine and none of the buttons respond.', timestamp: '00:24' },
      { id: 'th-223', speaker: 'ai', message: 'The child lock is active. Press and hold the "Rinse+Spin" buttons simultaneously for 3 seconds until you hear a chime.', timestamp: '00:48' },
      { id: 'th-224', speaker: 'customer', message: 'Heard the chime and the key icon vanished. All buttons work now!', timestamp: '01:12' },
    ],
    analysis: {
      intent: 'Product Issue',
      appliance: 'Washing Machine',
      issue: 'Child Lock toggle instruction',
      sentiment: 'Positive',
      priority: 'Low',
      confidence: 97,
      summary: 'Explained standard 3-second twin button child lock disable sequence.',
    },
    actionsTaken: [
      { id: 'a221', action: 'CHECK_CUSTOMER', description: 'Customer identified: Ananya Iyer', completed: true, timestamp: '00:03' },
    ],
  },
  {
    id: 'CALL-83897',
    customerId: 'CUST-1010',
    customerName: 'Kavita Reddy',
    customerPhone: '+91 98490 XXXXX',
    appliance: 'Refrigerator',
    applianceId: 'APP-2028',
    intent: 'Product Issue',
    issue: 'Refrigerator sides feel hot to touch',
    duration: '02:00',
    durationSeconds: 120,
    sentiment: 'Neutral',
    outcome: 'Resolved by AI',
    priority: 'Low',
    aiState: 'Completed',
    aiConfidence: 96,
    date: '4 days ago',
    transcript: [
      { id: 'th-231', speaker: 'ai', message: 'Welcome to HomeCare. How may I assist you today, Mrs. Reddy?', timestamp: '00:02' },
      { id: 'th-232', speaker: 'customer', message: 'The outer side walls of my new refrigerator are warm, almost hot to touch.', timestamp: '00:24' },
      { id: 'th-233', speaker: 'ai', message: 'Modern frost-free refrigerators have condenser cooling pipes embedded inside the side exterior walls to prevent external condensation. It is completely normal, especially during initial cooling or hot weather. Maintain 4 inches gap from surrounding walls.', timestamp: '00:58' },
    ],
    analysis: {
      intent: 'Product Issue',
      appliance: 'Refrigerator',
      issue: 'Side-wall condenser heat dissipation education',
      sentiment: 'Positive',
      priority: 'Low',
      confidence: 96,
      summary: 'Reassured customer regarding normal external skin condenser heat dissipation.',
    },
    actionsTaken: [
      { id: 'a231', action: 'CHECK_CUSTOMER', description: 'Customer identified: Kavita Reddy', completed: true, timestamp: '00:03' },
    ],
  },
  {
    id: 'CALL-83896',
    customerId: 'CUST-1011',
    customerName: 'Manoj Kumar',
    customerPhone: '+91 98188 XXXXX',
    appliance: 'Television',
    applianceId: 'APP-2029',
    intent: 'Order Status',
    issue: 'Track replacement remote delivery',
    duration: '01:10',
    durationSeconds: 70,
    sentiment: 'Neutral',
    outcome: 'Resolved by AI',
    priority: 'Low',
    aiState: 'Completed',
    aiConfidence: 98,
    date: '4 days ago',
    transcript: [
      { id: 'th-241', speaker: 'ai', message: 'Welcome to HomeCare support. How can I help you today, Mr. Kumar?', timestamp: '00:02' },
      { id: 'th-242', speaker: 'customer', message: 'I ordered a replacement smart remote last Monday. What is the tracking status?', timestamp: '00:22' },
      { id: 'th-243', speaker: 'ai', message: 'Your replacement remote is dispatched via BlueDart with tracking AWB 88192019. It is out for delivery today and will reach your address before 6 PM.', timestamp: '00:50' },
    ],
    analysis: {
      intent: 'Order Status',
      appliance: 'Television',
      issue: 'Courier dispatch tracking for accessory',
      sentiment: 'Positive',
      priority: 'Low',
      confidence: 98,
      summary: 'Provided real-time courier out-for-delivery status.',
    },
    actionsTaken: [
      { id: 'a241', action: 'CHECK_CUSTOMER', description: 'Customer identified: Manoj Kumar', completed: true, timestamp: '00:03' },
    ],
  },
  {
    id: 'CALL-83895',
    customerId: 'CUST-1012',
    customerName: 'Divya Nair',
    customerPhone: '+91 98470 XXXXX',
    appliance: 'Refrigerator',
    applianceId: 'APP-2031',
    intent: 'Warranty',
    issue: 'Inquire compressor warranty coverage',
    duration: '01:25',
    durationSeconds: 85,
    sentiment: 'Positive',
    outcome: 'Resolved by AI',
    priority: 'Low',
    aiState: 'Completed',
    aiConfidence: 97,
    date: '5 days ago',
    transcript: [
      { id: 'th-251', speaker: 'ai', message: 'Welcome to HomeCare. How may I assist you today, Ms. Nair?', timestamp: '00:02' },
      { id: 'th-252', speaker: 'customer', message: 'Is the smart inverter compressor on my refrigerator covered for 10 years?', timestamp: '00:22' },
      { id: 'th-253', speaker: 'ai', message: 'Yes! While the comprehensive machine warranty is 1 year, your LG Smart Inverter compressor has a dedicated 10-year manufacturer parts warranty active through January 2035.', timestamp: '00:50' },
    ],
    analysis: {
      intent: 'Warranty',
      appliance: 'Refrigerator',
      issue: '10-year inverter compressor warranty verification',
      sentiment: 'Positive',
      priority: 'Low',
      confidence: 97,
      summary: 'Confirmed 10-year compressor warranty coverage details.',
    },
    actionsTaken: [
      { id: 'a251', action: 'CHECK_CUSTOMER', description: 'Customer identified: Divya Nair', completed: true, timestamp: '00:03' },
    ],
  },
  {
    id: 'CALL-83894',
    customerId: 'CUST-1013',
    customerName: 'Suresh Joshi',
    customerPhone: '+91 98290 XXXXX',
    appliance: 'Air Conditioner',
    applianceId: 'APP-2002',
    intent: 'Refund',
    issue: 'Refund request for duplicate service invoice charge',
    duration: '02:50',
    durationSeconds: 170,
    sentiment: 'Frustrated',
    outcome: 'Human Escalation',
    priority: 'Medium',
    aiState: 'Completed',
    aiConfidence: 85,
    date: '5 days ago',
    transcript: [
      { id: 'th-261', speaker: 'ai', message: 'Welcome to HomeCare support. How may I assist you today, Mr. Joshi?', timestamp: '00:02' },
      { id: 'th-262', speaker: 'customer', message: 'I was charged twice on UPI for my AC gas recharge invoice INV-4019. I want an immediate refund.', timestamp: '00:26' },
      { id: 'th-263', speaker: 'ai', message: 'I see two duplicate transaction records for ₹2,400. To initiate instant bank charge reversal, our accounts team requires human authorization. Transferring you to our Billing Desk now.', timestamp: '01:05' },
    ],
    analysis: {
      intent: 'Refund',
      appliance: 'Air Conditioner',
      issue: 'Duplicate UPI payment charge reversal',
      sentiment: 'Frustrated',
      priority: 'Medium',
      confidence: 85,
      summary: 'Identified dual billing transaction and routed to financial supervisor for reversal processing.',
    },
    actionsTaken: [
      { id: 'a261', action: 'CHECK_CUSTOMER', description: 'Customer identified: Suresh Joshi', completed: true, timestamp: '00:03' },
      { id: 'a262', action: 'ESCALATE_HUMAN', description: 'Transferred to Accounts Specialist', completed: true, timestamp: '01:10' },
    ],
  },
  {
    id: 'CALL-83893',
    customerId: 'CUST-1014',
    customerName: 'Pooja Agarwal',
    customerPhone: '+91 98390 XXXXX',
    appliance: 'Water Purifier',
    applianceId: 'APP-2032',
    intent: 'Human Agent',
    issue: 'Customer requested evening callback after work hours',
    duration: '01:15',
    durationSeconds: 75,
    sentiment: 'Neutral',
    outcome: 'Callback Required',
    priority: 'Low',
    aiState: 'Completed',
    aiConfidence: 96,
    date: '6 days ago',
    transcript: [
      { id: 'th-271', speaker: 'ai', message: 'Welcome to HomeCare support. How can I help you today, Ms. Agarwal?', timestamp: '00:02' },
      { id: 'th-272', speaker: 'customer', message: 'I am entering an office meeting right now. Can someone call me back after 7 PM regarding my water purifier service?', timestamp: '00:24' },
      { id: 'th-273', speaker: 'ai', message: 'Certainly! I have scheduled an automated priority callback to your number today at 7:15 PM. You will receive an SMS reminder beforehand.', timestamp: '00:52' },
    ],
    analysis: {
      intent: 'Human Agent',
      appliance: 'Water Purifier',
      issue: 'Out-of-office callback request',
      sentiment: 'Neutral',
      priority: 'Low',
      confidence: 96,
      summary: 'Logged scheduled callback for evening window at customer preference.',
    },
    actionsTaken: [
      { id: 'a271', action: 'CHECK_CUSTOMER', description: 'Customer identified: Pooja Agarwal', completed: true, timestamp: '00:03' },
      { id: 'a272', action: 'CREATE_CALLBACK', description: 'Callback logged for 7:15 PM', completed: true, timestamp: '00:55' },
    ],
  },
  {
    id: 'CALL-83892',
    customerId: 'CUST-1015',
    customerName: 'Karthik Raman',
    customerPhone: '+91 98410 XXXXX',
    appliance: 'Air Conditioner',
    applianceId: 'APP-2004',
    intent: 'Product Issue',
    issue: 'Foul smell when AC first turned on',
    duration: '02:18',
    durationSeconds: 138,
    sentiment: 'Neutral',
    outcome: 'Resolved by AI',
    priority: 'Low',
    aiState: 'Completed',
    aiConfidence: 94,
    date: '6 days ago',
    transcript: [
      { id: 'th-281', speaker: 'ai', message: 'Welcome to HomeCare. How may I assist you today, Mr. Raman?', timestamp: '00:02' },
      { id: 'th-282', speaker: 'customer', message: 'When I turn on my AC, there is a sour musty smell for the first 5 minutes.', timestamp: '00:25' },
      { id: 'th-283', speaker: 'ai', message: 'Musty odor is caused by moisture accumulation on cooling coils. To eliminate it, run Fan Only mode for 15 minutes before switching off the AC to dry out the evaporator coil.', timestamp: '00:56' },
    ],
    analysis: {
      intent: 'Product Issue',
      appliance: 'Air Conditioner',
      issue: 'Coil mildew / moisture drying procedure',
      sentiment: 'Positive',
      priority: 'Low',
      confidence: 94,
      summary: 'Provided coil drying procedure to eliminate damp smell.',
    },
    actionsTaken: [
      { id: 'a281', action: 'CHECK_CUSTOMER', description: 'Customer identified: Karthik Raman', completed: true, timestamp: '00:03' },
    ],
  },
  {
    id: 'CALL-83891',
    customerId: 'CUST-1016',
    customerName: 'Meera Nambiar',
    customerPhone: '+91 98460 XXXXX',
    appliance: 'Television',
    applianceId: 'APP-2006',
    intent: 'Installation',
    issue: 'Soundbar optical cable configuration',
    duration: '02:00',
    durationSeconds: 120,
    sentiment: 'Positive',
    outcome: 'Resolved by AI',
    priority: 'Low',
    aiState: 'Completed',
    aiConfidence: 96,
    date: '1 week ago',
    transcript: [
      { id: 'th-291', speaker: 'ai', message: 'Welcome to HomeCare VIP support. How can I assist you today, Ms. Nambiar?', timestamp: '00:02' },
      { id: 'th-292', speaker: 'customer', message: 'I plugged an optical audio cable into my Sony TV but sound still comes from TV speakers.', timestamp: '00:25' },
      { id: 'th-293', speaker: 'ai', message: 'Open Quick Settings > Audio Output > change from TV Speakers to Audio System. Then ensure the plastic dust caps on both ends of the optical fiber cable are removed.', timestamp: '00:54' },
      { id: 'th-294', speaker: 'customer', message: 'I had left the clear cap on the optical tip! Removed it, selected Audio System, and it works wonderfully.', timestamp: '01:30' },
    ],
    analysis: {
      intent: 'Installation',
      appliance: 'Television',
      issue: 'Optical cable port cap and audio routing switch',
      sentiment: 'Positive',
      priority: 'Low',
      confidence: 96,
      summary: 'Identified unremoved optical tip protective cap and walked through TV audio menu.',
    },
    actionsTaken: [
      { id: 'a291', action: 'CHECK_CUSTOMER', description: 'Identified Meera Nambiar', completed: true, timestamp: '00:03' },
    ],
  },
];
