import { Customer } from '@/types';

export const mockCustomers: Customer[] = [
  {
    id: 'CUST-1001',
    name: 'Rahul Sharma',
    phone: '+91 98201 XXXXX',
    email: 'rahul.sharma@example.in',
    city: 'Mumbai',
    address: 'Flat 402, Sea Green Apts, Worli, Mumbai 400018',
    status: 'Active',
    customerSince: 'March 2025',
    activeAppliancesCount: 3,
    openRequestsCount: 1,
    lastContact: 'Just now',
  },
  {
    id: 'CUST-1002',
    name: 'Priya Mehta',
    phone: '+91 98114 XXXXX',
    email: 'priya.mehta@example.in',
    city: 'New Delhi',
    address: 'B-12, Greater Kailash Part 1, New Delhi 110048',
    status: 'Active',
    customerSince: 'January 2025',
    activeAppliancesCount: 2,
    openRequestsCount: 1,
    lastContact: '5 min ago',
  },
  {
    id: 'CUST-1003',
    name: 'Amit Verma',
    phone: '+91 98450 XXXXX',
    email: 'amit.verma@example.in',
    city: 'Bengaluru',
    address: '34, 4th Cross, Indiranagar 1st Stage, Bengaluru 560038',
    status: 'Active',
    customerSince: 'October 2024',
    activeAppliancesCount: 3,
    openRequestsCount: 0,
    lastContact: 'Yesterday',
  },
  {
    id: 'CUST-1004',
    name: 'Neha Kapoor',
    phone: '+91 98102 XXXXX',
    email: 'neha.kapoor@example.in',
    city: 'Gurugram',
    address: 'Tower C, 1104, DLF Phase 5, Gurugram 122009',
    status: 'VIP',
    customerSince: 'June 2024',
    activeAppliancesCount: 4,
    openRequestsCount: 1,
    lastContact: '12 min ago',
  },
  {
    id: 'CUST-1005',
    name: 'Arjun Singh',
    phone: '+91 97170 XXXXX',
    email: 'arjun.singh@example.in',
    city: 'Noida',
    address: 'Sector 62, Blossom Greens, Noida 201309',
    status: 'Active',
    customerSince: 'February 2025',
    activeAppliancesCount: 2,
    openRequestsCount: 0,
    lastContact: '3 days ago',
  },
  {
    id: 'CUST-1006',
    name: 'Sneha Patel',
    phone: '+91 98250 XXXXX',
    email: 'sneha.patel@example.in',
    city: 'Ahmedabad',
    address: '15, Satellite Heights, Bodakdev, Ahmedabad 380054',
    status: 'Active',
    customerSince: 'August 2024',
    activeAppliancesCount: 2,
    openRequestsCount: 1,
    lastContact: '1 hour ago',
  },
  {
    id: 'CUST-1007',
    name: 'Vikram Malhotra',
    phone: '+91 98300 XXXXX',
    email: 'vikram.m@example.in',
    city: 'Kolkata',
    address: '7B, Ballygunge Park Road, Kolkata 700019',
    status: 'Active',
    customerSince: 'April 2024',
    activeAppliancesCount: 3,
    openRequestsCount: 0,
    lastContact: '2 weeks ago',
  },
  {
    id: 'CUST-1008',
    name: 'Ananya Iyer',
    phone: '+91 98401 XXXXX',
    email: 'ananya.iyer@example.in',
    city: 'Chennai',
    address: '22, TTK Road, Alwarpet, Chennai 600018',
    status: 'VIP',
    customerSince: 'November 2024',
    activeAppliancesCount: 3,
    openRequestsCount: 1,
    lastContact: '20 min ago',
  },
  {
    id: 'CUST-1009',
    name: 'Rohan Deshmukh',
    phone: '+91 98220 XXXXX',
    email: 'rohan.d@example.in',
    city: 'Pune',
    address: 'Flat 801, Ivy Glen, Baner Road, Pune 411045',
    status: 'Active',
    customerSince: 'May 2025',
    activeAppliancesCount: 2,
    openRequestsCount: 0,
    lastContact: '5 days ago',
  },
  {
    id: 'CUST-1010',
    name: 'Kavita Reddy',
    phone: '+91 98490 XXXXX',
    email: 'kavita.reddy@example.in',
    city: 'Hyderabad',
    address: 'Plot 42, Jubilee Hills Road No. 36, Hyderabad 500033',
    status: 'Active',
    customerSince: 'December 2024',
    activeAppliancesCount: 4,
    openRequestsCount: 1,
    lastContact: '2 hours ago',
  },
  {
    id: 'CUST-1011',
    name: 'Manoj Kumar',
    phone: '+91 98188 XXXXX',
    email: 'manoj.kumar@example.in',
    city: 'New Delhi',
    address: 'C-40, Lajpat Nagar III, New Delhi 110024',
    status: 'Active',
    customerSince: 'July 2024',
    activeAppliancesCount: 2,
    openRequestsCount: 0,
    lastContact: '1 week ago',
  },
  {
    id: 'CUST-1012',
    name: 'Divya Nair',
    phone: '+91 98470 XXXXX',
    email: 'divya.nair@example.in',
    city: 'Kochi',
    address: '12/402, Skyline Imperial, Panampilly Nagar, Kochi 682036',
    status: 'Active',
    customerSince: 'January 2025',
    activeAppliancesCount: 1,
    openRequestsCount: 1,
    lastContact: '35 min ago',
  },
  {
    id: 'CUST-1013',
    name: 'Suresh Joshi',
    phone: '+91 98290 XXXXX',
    email: 'suresh.joshi@example.in',
    city: 'Jaipur',
    address: '45, Malviya Nagar Sector 4, Jaipur 302017',
    status: 'Active',
    customerSince: 'September 2024',
    activeAppliancesCount: 2,
    openRequestsCount: 0,
    lastContact: '4 days ago',
  },
  {
    id: 'CUST-1014',
    name: 'Pooja Agarwal',
    phone: '+91 98390 XXXXX',
    email: 'pooja.agarwal@example.in',
    city: 'Lucknow',
    address: 'B-24, Gomti Nagar Phase 2, Lucknow 226010',
    status: 'Active',
    customerSince: 'October 2024',
    activeAppliancesCount: 2,
    openRequestsCount: 1,
    lastContact: '3 hours ago',
  },
  {
    id: 'CUST-1015',
    name: 'Karthik Raman',
    phone: '+91 98410 XXXXX',
    email: 'karthik.r@example.in',
    city: 'Chennai',
    address: 'Flat 3A, Olive Residency, Adyar, Chennai 600020',
    status: 'Active',
    customerSince: 'February 2025',
    activeAppliancesCount: 3,
    openRequestsCount: 0,
    lastContact: '6 days ago',
  },
  {
    id: 'CUST-1016',
    name: 'Meera Nambiar',
    phone: '+91 98460 XXXXX',
    email: 'meera.nambiar@example.in',
    city: 'Bengaluru',
    address: '108, Prestige Silver Oak, Whitefield, Bengaluru 560066',
    status: 'VIP',
    customerSince: 'March 2024',
    activeAppliancesCount: 3,
    openRequestsCount: 1,
    lastContact: '15 min ago',
  },
  {
    id: 'CUST-1017',
    name: 'Alok Saxena',
    phone: '+91 98111 XXXXX',
    email: 'alok.saxena@example.in',
    city: 'New Delhi',
    address: 'E-14, Vasant Vihar, New Delhi 110057',
    status: 'Active',
    customerSince: 'May 2024',
    activeAppliancesCount: 2,
    openRequestsCount: 0,
    lastContact: '1 month ago',
  },
  {
    id: 'CUST-1018',
    name: 'Shreya Chatterjee',
    phone: '+91 98310 XXXXX',
    email: 'shreya.c@example.in',
    city: 'Kolkata',
    address: 'Flat 5C, South City Towers, Prince Anwar Shah Rd, Kolkata 700068',
    status: 'Active',
    customerSince: 'November 2024',
    activeAppliancesCount: 2,
    openRequestsCount: 1,
    lastContact: '45 min ago',
  },
  {
    id: 'CUST-1019',
    name: 'Gaurav Bhatia',
    phone: '+91 98720 XXXXX',
    email: 'gaurav.b@example.in',
    city: 'Chandigarh',
    address: 'House 524, Sector 18-B, Chandigarh 160018',
    status: 'Active',
    customerSince: 'August 2024',
    activeAppliancesCount: 2,
    openRequestsCount: 0,
    lastContact: '2 weeks ago',
  },
  {
    id: 'CUST-1020',
    name: 'Ritu Sen',
    phone: '+91 98305 XXXXX',
    email: 'ritu.sen@example.in',
    city: 'Kolkata',
    address: '28, Salt Lake Sector 2, Kolkata 700091',
    status: 'Active',
    customerSince: 'January 2025',
    activeAppliancesCount: 1,
    openRequestsCount: 1,
    lastContact: '4 hours ago',
  },
  {
    id: 'CUST-1021',
    name: 'Deepak Choudhary',
    phone: '+91 98292 XXXXX',
    email: 'deepak.c@example.in',
    city: 'Jaipur',
    address: 'Plot 78, C-Scheme, Jaipur 302001',
    status: 'Active',
    customerSince: 'February 2025',
    activeAppliancesCount: 2,
    openRequestsCount: 0,
    lastContact: '10 days ago',
  },
  {
    id: 'CUST-1022',
    name: 'Tarun Sengupta',
    phone: '+91 98205 XXXXX',
    email: 'tarun.s@example.in',
    city: 'Mumbai',
    address: 'Flat 1201, Oberoi Woods, Goregaon East, Mumbai 400063',
    status: 'Active',
    customerSince: 'June 2024',
    activeAppliancesCount: 3,
    openRequestsCount: 0,
    lastContact: '3 weeks ago',
  },
];
