import { ServiceRequest } from '@/types';

export const mockServiceRequests: ServiceRequest[] = [
  {
    id: 'SR-10482',
    callId: 'CALL-83921',
    customerId: 'CUST-1001',
    customerName: 'Rahul Sharma',
    customerPhone: '+91 98201 XXXXX',
    customerAddress: 'Flat 402, Sea Green Apts, Worli, Mumbai 400018',
    appliance: 'Washing Machine',
    applianceId: 'APP-2001',
    brand: 'Samsung',
    model: 'WW80T504DAN (8.0 kg Front Load)',
    issue: 'Excessive vibration during spin cycle',
    priority: 'Medium',
    status: 'New',
    created: '2 min ago',
    createdAt: 'Today, 20:18',
    aiSummary: 'Customer reported loud noise and significant movement during the washing machine spin cycle. Appliance moved several inches on floor.',
    recommendedAction: 'Technician Inspection (Drum suspension damper check and transit bolt verification)',
    timeline: [
      { id: 't-1', title: 'Session started', description: 'Customer support session connected to AI agent', timestamp: '20:16', status: 'completed' },
      { id: 't-2', title: 'Issue identified', description: 'AI categorized problem as excessive mechanical vibration', timestamp: '20:17', status: 'completed' },
      { id: 't-3', title: 'Service request created', description: 'Ticket generated with medium priority under active warranty', timestamp: '20:18', status: 'completed' },
      { id: 't-4', title: 'Awaiting technician assignment', description: 'System routing to Mumbai Worli service hub', timestamp: '20:19', status: 'current' },
    ],
  },
  {
    id: 'SR-10481',
    callId: 'CALL-83922',
    customerId: 'CUST-1002',
    customerName: 'Priya Mehta',
    customerPhone: '+91 98114 XXXXX',
    customerAddress: 'B-12, Greater Kailash Part 1, New Delhi 110048',
    appliance: 'Air Conditioner',
    applianceId: 'APP-2004',
    brand: 'Daikin',
    model: 'FTKF50TV (1.5 Ton Split)',
    issue: 'AC running but blowing room temperature air',
    priority: 'High',
    status: 'Assigned',
    assignedTechnician: 'Vikram Joshi (Badge #DL-8821)',
    scheduledDate: 'Tomorrow, 10:30 AM',
    created: '8 min ago',
    createdAt: 'Today, 20:12',
    aiSummary: 'Customer reported 1.5T Daikin split AC failing to produce cooling. Diagnostic check determined outdoor compressor fan fails to initiate rotation.',
    recommendedAction: 'Refrigerant pressure leak detection and run-capacitor electrical load test',
    timeline: [
      { id: 't-11', title: 'Support Session Started', description: 'Customer initiated contact through the website', timestamp: '20:10', status: 'completed' },
      { id: 't-12', title: 'Diagnostic Completed', description: 'AI verified outdoor unit inactivity', timestamp: '20:11', status: 'completed' },
      { id: 't-13', title: 'Ticket Generated', description: 'High-priority warranty service order raised', timestamp: '20:12', status: 'completed' },
      { id: 't-14', title: 'Technician Assigned', description: 'Assigned to senior HVAC technician Vikram Joshi', timestamp: '20:15', status: 'current' },
    ],
  },
  {
    id: 'SR-10480',
    callId: 'CALL-83924',
    customerId: 'CUST-1008',
    customerName: 'Ananya Iyer',
    customerPhone: '+91 98401 XXXXX',
    customerAddress: '22, TTK Road, Alwarpet, Chennai 600018',
    appliance: 'Air Conditioner',
    applianceId: 'APP-2021',
    brand: 'Carrier',
    model: 'CAI18ER3R30F0 (1.5 Ton Inverter)',
    issue: 'Water dripping continuously from indoor AC unit',
    priority: 'High',
    status: 'Technician Scheduled',
    assignedTechnician: 'K. Murugan (Badge #CH-4412)',
    scheduledDate: 'Tomorrow, 09:00 AM',
    created: '20 min ago',
    createdAt: 'Today, 20:00',
    aiSummary: 'Indoor unit condensating water leaking profusely onto wooden flooring. Customer advised to disconnect main power switch immediately.',
    recommendedAction: 'Drain pipe unclogging, U-trap flush, and drain pan realignment',
    timeline: [
      { id: 't-21', title: 'Emergency Call Received', description: 'AI identified water damage risk', timestamp: '19:58', status: 'completed' },
      { id: 't-22', title: 'Safety Cutoff Advised', description: 'Customer confirmed power isolation', timestamp: '19:59', status: 'completed' },
      { id: 't-23', title: 'Priority Dispatch Scheduled', description: 'Technician assigned for early morning first slot', timestamp: '20:05', status: 'completed' },
      { id: 't-24', title: 'En Route to Dispatch', description: 'Awaiting technician departure', timestamp: '20:10', status: 'current' },
    ],
  },
  {
    id: 'SR-10479',
    callId: 'CALL-83916',
    customerId: 'CUST-1011',
    customerName: 'Manoj Kumar',
    customerPhone: '+91 98188 XXXXX',
    customerAddress: 'C-40, Lajpat Nagar III, New Delhi 110024',
    appliance: 'Washing Machine',
    applianceId: 'APP-2030',
    brand: 'Whirlpool',
    model: 'Stainwash Ultra (8.0 kg)',
    issue: 'Burning smell and motor stopped abruptly',
    priority: 'Critical',
    status: 'Assigned',
    assignedTechnician: 'Satish Tyagi (Badge #DL-1092)',
    scheduledDate: 'Tomorrow, 09:30 AM',
    created: '3 hours ago',
    createdAt: 'Today, 17:35',
    aiSummary: 'Electrical burning odor and sudden drum arrest during rinse cycle. Customer isolated power supply on AI recommendation.',
    recommendedAction: 'Drive motor windings insulation resistance test and main control board relay inspection',
    timeline: [
      { id: 't-31', title: 'Critical Alert Raised', description: 'AI flagged fire safety hazard', timestamp: '17:35', status: 'completed' },
      { id: 't-32', title: 'Urgent Ticket Logged', description: 'Supervisor bypassed standard queue', timestamp: '17:38', status: 'completed' },
      { id: 't-33', title: 'Certified Tech Assigned', description: 'Senior technician Satish Tyagi allocated', timestamp: '17:45', status: 'current' },
    ],
  },
  {
    id: 'SR-10478',
    callId: 'CALL-83915',
    customerId: 'CUST-1012',
    customerName: 'Divya Nair',
    customerPhone: '+91 98470 XXXXX',
    customerAddress: '12/402, Skyline Imperial, Panampilly Nagar, Kochi 682036',
    appliance: 'Refrigerator',
    applianceId: 'APP-2031',
    brand: 'LG',
    model: 'GL-S292RDSY (242 Litres)',
    issue: 'Excessive frost buildup on freezer walls',
    priority: 'Medium',
    status: 'Technician Scheduled',
    assignedTechnician: 'Jinto Thomas (Badge #KC-2291)',
    scheduledDate: 'Tomorrow, 02:00 PM',
    created: '3.5 hours ago',
    createdAt: 'Today, 17:02',
    aiSummary: 'Customer reported ice buildup in frost-free unit restricting airflow. Rubber gasket reported intact.',
    recommendedAction: 'Defrost timer replacement and bi-metal thermal cut-off sensor testing',
    timeline: [
      { id: 't-41', title: 'Ticket Logged', description: 'AI created warranty request', timestamp: '17:02', status: 'completed' },
      { id: 't-42', title: 'Technician Scheduled', description: 'Jinto Thomas assigned with replacement defrost heater kit', timestamp: '17:30', status: 'completed' },
      { id: 't-43', title: 'Customer Notified', description: 'SMS confirmation dispatched', timestamp: '17:31', status: 'current' },
    ],
  },
  {
    id: 'SR-10477',
    callId: 'CALL-83914',
    customerId: 'CUST-1014',
    customerName: 'Pooja Agarwal',
    customerPhone: '+91 98390 XXXXX',
    customerAddress: 'B-24, Gomti Nagar Phase 2, Lucknow 226010',
    appliance: 'Water Purifier',
    applianceId: 'APP-2032',
    brand: 'Kent',
    model: 'Supreme Alkaline RO (8 Litres)',
    issue: 'Beeping alarm on Kent RO (UV failure)',
    priority: 'Medium',
    status: 'In Progress',
    assignedTechnician: 'Mohd. Rizwan (Badge #LK-7712)',
    scheduledDate: 'Today, 06:00 PM',
    created: '4 hours ago',
    createdAt: 'Today, 16:20',
    aiSummary: 'Customer reported 2 beeps per 2 seconds audio warning. Identified as UV disinfection lamp fault.',
    recommendedAction: 'UV chamber lamp replacement and TDS level calibration',
    timeline: [
      { id: 't-51', title: 'Ticket Logged', description: 'AI generated ticket with acoustic symptom match', timestamp: '16:20', status: 'completed' },
      { id: 't-52', title: 'Assigned', description: 'Allocated to water systems specialist', timestamp: '16:35', status: 'completed' },
      { id: 't-53', title: 'In Progress', description: 'Technician on site inspecting purifier unit', timestamp: '18:15', status: 'current' },
    ],
  },
  {
    id: 'SR-10470',
    callId: 'CALL-83913',
    customerId: 'CUST-1013',
    customerName: 'Suresh Joshi',
    customerPhone: '+91 98290 XXXXX',
    customerAddress: '45, Malviya Nagar Sector 4, Jaipur 302017',
    appliance: 'Air Conditioner',
    applianceId: 'APP-2002',
    brand: 'LG',
    model: 'KS-Q18ENZA (1.5 Ton)',
    issue: 'Scheduled preventative seasonal AC maintenance',
    priority: 'Low',
    status: 'Resolved',
    assignedTechnician: 'Ramesh Kumar (Badge #JP-5510)',
    scheduledDate: 'Today, 03:00 PM',
    created: '5 hours ago',
    createdAt: 'Today, 15:45',
    aiSummary: 'Pre-summer preventative deep jet clean, coil wash, and gas pressure verification.',
    recommendedAction: 'High pressure foam wash and operating amp draw test',
    timeline: [
      { id: 't-61', title: 'Request Created', description: 'Annual maintenance order logged', timestamp: '11:00', status: 'completed' },
      { id: 't-62', title: 'Service Dispatched', description: 'Technician arrived at site', timestamp: '15:15', status: 'completed' },
      { id: 't-63', title: 'Maintenance Finished', description: 'Pressure checked 125 PSI; cooling at 14°C vent discharge', timestamp: '16:40', status: 'completed' },
      { id: 't-64', title: 'Signed Off', description: 'Customer rated 5 stars via mobile OTP', timestamp: '16:45', status: 'completed' },
    ],
  },
  {
    id: 'SR-10468',
    callId: 'CALL-83911',
    customerId: 'CUST-1017',
    customerName: 'Alok Saxena',
    customerPhone: '+91 98111 XXXXX',
    customerAddress: 'E-14, Vasant Vihar, New Delhi 110057',
    appliance: 'Air Conditioner',
    applianceId: 'APP-2009',
    brand: 'Voltas',
    model: '185V Vectra Elite',
    issue: 'AC uninstallation and relocation mounting',
    priority: 'Low',
    status: 'Assigned',
    assignedTechnician: 'Harish Chander (Badge #DL-3391)',
    scheduledDate: 'Saturday, 10:00 AM',
    created: '6 hours ago',
    createdAt: 'Today, 14:30',
    aiSummary: 'Customer scheduled AC uninstallation from Vasant Vihar and reinstallation at new home.',
    recommendedAction: 'Gas pump down lock, unmount indoor/outdoor units, and re-mount with copper test',
    timeline: [
      { id: 't-71', title: 'Booking Received', description: 'Relocation package booked via AI voice agent', timestamp: '14:30', status: 'completed' },
      { id: 't-72', title: 'Technician Assigned', description: 'Harish Chander booked for Saturday morning slot', timestamp: '14:45', status: 'current' },
    ],
  },
  {
    id: 'SR-10465',
    callId: 'CALL-83909',
    customerId: 'CUST-1019',
    customerName: 'Gaurav Bhatia',
    customerPhone: '+91 98720 XXXXX',
    customerAddress: 'House 524, Sector 18-B, Chandigarh 160018',
    appliance: 'Water Purifier',
    applianceId: 'APP-2005',
    brand: 'Kent',
    model: 'Grand Plus RO+UV+UF',
    issue: 'Extremely slow RO water dispense flow',
    priority: 'Medium',
    status: 'Technician Scheduled',
    assignedTechnician: 'Simranjit Singh (Badge #CH-8801)',
    scheduledDate: 'Tomorrow, 11:00 AM',
    created: '7 hours ago',
    createdAt: 'Today, 13:15',
    aiSummary: 'Customer reported dispense time exceeding 30 minutes per bottle. Filters in place over 10 months.',
    recommendedAction: 'Complete RO membrane and sediment block replacement',
    timeline: [
      { id: 't-81', title: 'Call Completed', description: 'AI matched slow flow to filter saturation', timestamp: '13:15', status: 'completed' },
      { id: 't-82', title: 'Parts Allocated', description: 'Original Kent cartridge kit picked from Chandigarh warehouse', timestamp: '13:40', status: 'completed' },
      { id: 't-83', title: 'Visit Confirmed', description: 'Appointment locked for tomorrow 11 AM', timestamp: '14:00', status: 'current' },
    ],
  },
  {
    id: 'SR-10463',
    callId: 'CALL-83908',
    customerId: 'CUST-1020',
    customerName: 'Ritu Sen',
    customerPhone: '+91 98305 XXXXX',
    customerAddress: '28, Salt Lake Sector 2, Kolkata 700091',
    appliance: 'Air Conditioner',
    applianceId: 'APP-2004',
    brand: 'Daikin',
    model: 'FTKF50TV',
    issue: 'AC unit making rattling sound from blower fan',
    priority: 'Medium',
    status: 'In Progress',
    assignedTechnician: 'Subhash Bose (Badge #KL-9902)',
    scheduledDate: 'Today, 05:00 PM',
    created: '8 hours ago',
    createdAt: 'Today, 12:40',
    aiSummary: 'Rattling noise proportional to fan speed setting. AI diagnosed loose blower rotor wheel.',
    recommendedAction: 'Disassemble indoor casing, balance blower fan wheel, and lube bearings',
    timeline: [
      { id: 't-91', title: 'Request Created', description: 'Ticket created through AI support', timestamp: '12:40', status: 'completed' },
      { id: 't-92', title: 'Technician Dispatched', description: 'Subhash Bose allocated from Salt Lake zone', timestamp: '13:00', status: 'completed' },
      { id: 't-93', title: 'Work in Progress', description: 'Technician on site inspecting fan assembly', timestamp: '17:10', status: 'current' },
    ],
  },
  {
    id: 'SR-10459',
    callId: 'CALL-83902',
    customerId: 'CUST-1004',
    customerName: 'Neha Kapoor',
    customerPhone: '+91 98102 XXXXX',
    customerAddress: 'Tower C, 1104, DLF Phase 5, Gurugram 122009',
    appliance: 'Television',
    applianceId: 'APP-2012',
    brand: 'Samsung',
    model: 'QA65Q60CAKLXL (65 Inch QLED)',
    issue: 'Wall mount bracket loose when tilting',
    priority: 'Medium',
    status: 'Technician Scheduled',
    assignedTechnician: 'Ashok Yadav (Badge #GG-1102)',
    scheduledDate: 'Tomorrow, 03:00 PM',
    created: '1 day ago',
    createdAt: 'Yesterday, 11:20',
    aiSummary: 'Swivel bracket holding 65-inch panel needs anchor bolt tightening into masonry wall.',
    recommendedAction: 'Anchor bolt reinforcement with heavy-duty metal expansion sleeve fasteners',
    timeline: [
      { id: 't-101', title: 'Safety Logged', description: 'AI prioritized panel fall hazard', timestamp: '11:20', status: 'completed' },
      { id: 't-102', title: 'Technician Scheduled', description: 'Heavy appliance specialist assigned', timestamp: '11:50', status: 'current' },
    ],
  },
  {
    id: 'SR-10455',
    callId: 'CALL-83901',
    customerId: 'CUST-1005',
    customerName: 'Arjun Singh',
    customerPhone: '+91 97170 XXXXX',
    customerAddress: 'Sector 62, Blossom Greens, Noida 201309',
    appliance: 'Air Conditioner',
    applianceId: 'APP-2014',
    brand: 'Hitachi',
    model: 'RAW318HFDO (1.5 Ton Window AC)',
    issue: 'Window AC compressor cycling on and off every 2 minutes',
    priority: 'High',
    status: 'In Progress',
    assignedTechnician: 'Pramod Kumar (Badge #ND-4419)',
    scheduledDate: 'Today, 04:30 PM',
    created: '2 days ago',
    createdAt: '2 days ago, 10:15',
    aiSummary: 'Short cycling resulting in elevated humidity and poor cooling in master bedroom.',
    recommendedAction: 'Clean rear condenser fins and replace faulty thermostat sensor probe',
    timeline: [
      { id: 't-111', title: 'Logged via AI', description: 'Created with high priority', timestamp: '10:15', status: 'completed' },
      { id: 't-112', title: 'Diagnosis in Progress', description: 'Technician currently testing amp draw', timestamp: '16:45', status: 'current' },
    ],
  },
  {
    id: 'SR-10452',
    callId: 'CALL-83900',
    customerId: 'CUST-1006',
    customerName: 'Sneha Patel',
    customerPhone: '+91 98250 XXXXX',
    customerAddress: '15, Satellite Heights, Bodakdev, Ahmedabad 380054',
    appliance: 'Water Purifier',
    applianceId: 'APP-2016',
    brand: 'Kent',
    model: 'Prime Plus RO',
    issue: 'Taste of purified water is slightly metallic',
    priority: 'Medium',
    status: 'Resolved',
    assignedTechnician: 'Bhavin Shah (Badge #AH-3301)',
    scheduledDate: 'Yesterday, 02:00 PM',
    created: '2 days ago',
    createdAt: '2 days ago, 09:30',
    aiSummary: 'Customer noticed altered mineral taste. AI recommended calibrated TDS testing.',
    recommendedAction: 'Post-carbon filter replaced and output TDS stabilized at 90 ppm',
    timeline: [
      { id: 't-121', title: 'Ticket Logged', description: 'Recorded taste complaint', timestamp: '09:30', status: 'completed' },
      { id: 't-122', title: 'Service Executed', description: 'Bhavin Shah flushed system and installed fresh cartridge', timestamp: '14:20', status: 'completed' },
      { id: 't-123', title: 'Resolved', description: 'TDS tested 88 ppm; customer verified taste normal', timestamp: '15:10', status: 'completed' },
    ],
  },
  {
    id: 'SR-10448',
    customerId: 'CUST-1007',
    customerName: 'Vikram Malhotra',
    customerPhone: '+91 98300 XXXXX',
    customerAddress: '7B, Ballygunge Park Road, Kolkata 700019',
    appliance: 'Refrigerator',
    applianceId: 'APP-2019',
    brand: 'Haier',
    model: 'HRB-3654POG-E',
    issue: 'Vegetable crisper drawer freezing produce',
    priority: 'Low',
    status: 'Closed',
    assignedTechnician: 'Debashis Roy (Badge #KL-1192)',
    scheduledDate: '3 days ago',
    created: '4 days ago',
    createdAt: '4 days ago, 11:00',
    aiSummary: 'Air damper flap stuck in open position directing sub-zero air into bottom crisper drawer.',
    recommendedAction: 'Replaced motorized baffle air damper flap',
    timeline: [
      { id: 't-131', title: 'Created', description: 'Complaint logged', timestamp: '11:00', status: 'completed' },
      { id: 't-132', title: 'Part Installed', description: 'Damper replaced under Haier warranty', timestamp: '15:00', status: 'completed' },
      { id: 't-133', title: 'Closed', description: 'Post-service 48hr follow-up confirmed temperature stable at 4°C', timestamp: '17:00', status: 'completed' },
    ],
  },
  {
    id: 'SR-10440',
    customerId: 'CUST-1009',
    customerName: 'Rohan Deshmukh',
    customerPhone: '+91 98220 XXXXX',
    customerAddress: 'Flat 801, Ivy Glen, Baner Road, Pune 411045',
    appliance: 'Refrigerator',
    applianceId: 'APP-2023',
    brand: 'Samsung',
    model: 'RT28C3733S8',
    issue: 'Gasket seal tearing along bottom edge',
    priority: 'Low',
    status: 'Closed',
    assignedTechnician: 'Nilesh Patil (Badge #PN-2210)',
    scheduledDate: '5 days ago',
    created: '6 days ago',
    createdAt: '6 days ago, 14:00',
    aiSummary: 'Customer noticed moisture on exterior due to torn door gasket.',
    recommendedAction: 'OEM magnetic door rubber gasket replacement',
    timeline: [
      { id: 't-141', title: 'Request Created', description: 'Gasket replacement requested', timestamp: '14:00', status: 'completed' },
      { id: 't-142', title: 'Replacement Done', description: 'New seal fitted and vacuum tested', timestamp: '16:30', status: 'completed' },
      { id: 't-143', title: 'Closed', description: 'Customer confirmed no air leak', timestamp: '18:00', status: 'completed' },
    ],
  },
  {
    id: 'SR-10435',
    customerId: 'CUST-1010',
    customerName: 'Kavita Reddy',
    customerPhone: '+91 98490 XXXXX',
    customerAddress: 'Plot 42, Jubilee Hills Road No. 36, Hyderabad 500033',
    appliance: 'Air Conditioner',
    applianceId: 'APP-2025',
    brand: 'Blue Star',
    model: 'IC318EBTU',
    issue: 'Remote control not syncing with indoor unit',
    priority: 'Medium',
    status: 'In Progress',
    assignedTechnician: 'Chandra Shekar (Badge #HY-8891)',
    scheduledDate: 'Today, 03:00 PM',
    created: '2 hours ago',
    createdAt: 'Today, 18:20',
    aiSummary: 'Display PCB receiver failed to recognize IR commands despite remote emitter functioning.',
    recommendedAction: 'Replace indoor unit IR receiver PCB display module',
    timeline: [
      { id: 't-151', title: 'Logged', description: 'Raised via customer support call', timestamp: '18:20', status: 'completed' },
      { id: 't-152', title: 'In Progress', description: 'Technician on site replacing sensor board', timestamp: '19:40', status: 'current' },
    ],
  },
  {
    id: 'SR-10430',
    customerId: 'CUST-1015',
    customerName: 'Karthik Raman',
    customerPhone: '+91 98410 XXXXX',
    customerAddress: 'Flat 3A, Olive Residency, Adyar, Chennai 600020',
    appliance: 'Washing Machine',
    applianceId: 'APP-2001',
    brand: 'Samsung',
    model: 'WW80T504DAN',
    issue: 'Detergent drawer leaking water during fill cycle',
    priority: 'Low',
    status: 'Resolved',
    assignedTechnician: 'Senthil Nathan (Badge #CH-1920)',
    scheduledDate: 'Yesterday, 11:00 AM',
    created: '2 days ago',
    createdAt: '2 days ago, 15:00',
    aiSummary: 'Water overflowing from soap dispenser compartment onto front fascia.',
    recommendedAction: 'Cleaned siphon spray nozzles and removed clogged powder residue',
    timeline: [
      { id: 't-161', title: 'Created', description: 'Complaint registered', timestamp: '15:00', status: 'completed' },
      { id: 't-162', title: 'Resolved', description: 'Spray jets cleared; test cycle ran without leak', timestamp: '12:00', status: 'completed' },
    ],
  },
  {
    id: 'SR-10425',
    customerId: 'CUST-1016',
    customerName: 'Meera Nambiar',
    customerPhone: '+91 98460 XXXXX',
    customerAddress: '108, Prestige Silver Oak, Whitefield, Bengaluru 560066',
    appliance: 'Washing Machine',
    applianceId: 'APP-2020',
    brand: 'LG',
    model: 'FHM1207SDW',
    issue: 'Drum not spinning / OE drain error code',
    priority: 'High',
    status: 'In Progress',
    assignedTechnician: 'Vinod Hegde (Badge #BL-9012)',
    scheduledDate: 'Today, 06:30 PM',
    created: '5 hours ago',
    createdAt: 'Today, 15:10',
    aiSummary: 'OE code flashing and water retained in tub. Repeat escalation customer.',
    recommendedAction: 'Inspect drain pump impeller for foreign coin blockage and check drain hose kink',
    timeline: [
      { id: 't-171', title: 'Escalated', description: 'Priority dispatched directly by manager', timestamp: '15:15', status: 'completed' },
      { id: 't-172', title: 'On Site', description: 'Technician currently disassembling drain pump', timestamp: '18:50', status: 'current' },
    ],
  },
  {
    id: 'SR-10420',
    customerId: 'CUST-1018',
    customerName: 'Shreya Chatterjee',
    customerPhone: '+91 98310 XXXXX',
    customerAddress: 'Flat 5C, South City Towers, Prince Anwar Shah Rd, Kolkata 700068',
    appliance: 'Refrigerator',
    applianceId: 'APP-2019',
    brand: 'Haier',
    model: 'HRB-3654POG-E',
    issue: 'Interior LED light bulb extinguished',
    priority: 'Low',
    status: 'Resolved',
    assignedTechnician: 'Arindam Ghosh (Badge #KL-4401)',
    scheduledDate: 'Yesterday, 04:00 PM',
    created: '3 days ago',
    createdAt: '3 days ago, 12:00',
    aiSummary: 'Internal compartment dark when opening main door.',
    recommendedAction: 'Replaced 12V DC interior LED strip assembly',
    timeline: [
      { id: 't-181', title: 'Logged', description: 'Ticket created', timestamp: '12:00', status: 'completed' },
      { id: 't-182', title: 'Resolved', description: 'LED assembly replaced', timestamp: '16:30', status: 'completed' },
    ],
  },
  {
    id: 'SR-10415',
    customerId: 'CUST-1021',
    customerName: 'Deepak Choudhary',
    customerPhone: '+91 98292 XXXXX',
    customerAddress: 'Plot 78, C-Scheme, Jaipur 302001',
    appliance: 'Television',
    applianceId: 'APP-2006',
    brand: 'Sony',
    model: 'Bravia KD-55X74L',
    issue: 'Vertical colored line on LED panel display',
    priority: 'High',
    status: 'Assigned',
    assignedTechnician: 'Sunil Meena (Badge #JP-7719)',
    scheduledDate: 'Tomorrow, 12:00 PM',
    created: '8 hours ago',
    createdAt: 'Today, 12:05',
    aiSummary: 'Single purple vertical pixel line down right side of 55-inch panel.',
    recommendedAction: 'T-CON board ribbon cable test and possible panel module replacement under warranty',
    timeline: [
      { id: 't-191', title: 'Created', description: 'Logged with photo verification via SMS', timestamp: '12:05', status: 'completed' },
      { id: 't-192', title: 'Assigned', description: 'Panel specialist Sunil Meena assigned', timestamp: '12:35', status: 'current' },
    ],
  },
  {
    id: 'SR-10410',
    customerId: 'CUST-1022',
    customerName: 'Tarun Sengupta',
    customerPhone: '+91 98205 XXXXX',
    customerAddress: 'Flat 1201, Oberoi Woods, Goregaon East, Mumbai 400063',
    appliance: 'Washing Machine',
    applianceId: 'APP-2001',
    brand: 'Samsung',
    model: 'WW80T504DAN',
    issue: 'Water inlet valve slow fill error (4C code)',
    priority: 'Medium',
    status: 'Closed',
    assignedTechnician: 'Ganesh More (Badge #MB-3301)',
    scheduledDate: '4 days ago',
    created: '5 days ago',
    createdAt: '5 days ago, 10:00',
    aiSummary: 'Machine taking over 20 minutes to fill with water and flashing 4C.',
    recommendedAction: 'Cleaned wire mesh filter in cold water inlet valve',
    timeline: [
      { id: 't-201', title: 'Completed', description: 'Valve cleaned and flow rate restored to 12 L/min', timestamp: '12:00', status: 'completed' },
    ],
  },
  {
    id: 'SR-10405',
    customerId: 'CUST-1003',
    customerName: 'Amit Verma',
    customerPhone: '+91 98450 XXXXX',
    customerAddress: '34, 4th Cross, Indiranagar 1st Stage, Bengaluru 560038',
    appliance: 'Refrigerator',
    applianceId: 'APP-2008',
    brand: 'LG',
    model: 'GL-T432APZY',
    issue: 'Ice maker twist tray cracked',
    priority: 'Low',
    status: 'Closed',
    assignedTechnician: 'Prasad Rao (Badge #BL-1109)',
    scheduledDate: '1 week ago',
    created: '8 days ago',
    createdAt: '8 days ago, 16:00',
    aiSummary: 'Plastic manual twist ice maker tray cracked during ice dispensing.',
    recommendedAction: 'Delivered replacement twist ice maker assembly',
    timeline: [
      { id: 't-211', title: 'Delivered and Closed', description: 'Replaced with genuine LG part', timestamp: '14:00', status: 'completed' },
    ],
  },
  {
    id: 'SR-10400',
    customerId: 'CUST-1005',
    customerName: 'Arjun Singh',
    customerPhone: '+91 97170 XXXXX',
    customerAddress: 'Sector 62, Blossom Greens, Noida 201309',
    appliance: 'Refrigerator',
    applianceId: 'APP-2013',
    brand: 'Samsung',
    model: 'RT37C4512S8',
    issue: 'Door alarm beeping with door closed',
    priority: 'Low',
    status: 'Resolved',
    assignedTechnician: 'Dharmendra Sharma (Badge #ND-8820)',
    scheduledDate: 'Yesterday, 03:00 PM',
    created: '2 days ago',
    createdAt: '2 days ago, 11:00',
    aiSummary: 'Reed switch magnetic sensor not triggering closure on bottom door.',
    recommendedAction: 'Adjusted door hinge alignment and replaced magnetic sensor',
    timeline: [
      { id: 't-221', title: 'Resolved', description: 'Sensor replaced; buzzer silence verified', timestamp: '16:00', status: 'completed' },
    ],
  },
  {
    id: 'SR-10395',
    customerId: 'CUST-1007',
    customerName: 'Vikram Malhotra',
    customerPhone: '+91 98300 XXXXX',
    customerAddress: '7B, Ballygunge Park Road, Kolkata 700019',
    appliance: 'Air Conditioner',
    applianceId: 'APP-2017',
    brand: 'Mitsubishi',
    model: 'MSY-JS18VF',
    issue: 'Scheduled seasonal filter jet cleaning',
    priority: 'Low',
    status: 'Resolved',
    assignedTechnician: 'Ranjan Mondal (Badge #KL-7721)',
    scheduledDate: 'Yesterday, 10:00 AM',
    created: '3 days ago',
    createdAt: '3 days ago, 09:00',
    aiSummary: 'Pre-monsoon maintenance and anti-bacterial coil treatment.',
    recommendedAction: 'Eco-clean foam application and drain flush',
    timeline: [
      { id: 't-231', title: 'Resolved', description: 'Full service completed under AMC contract', timestamp: '11:45', status: 'completed' },
    ],
  },
  {
    id: 'SR-10390',
    customerId: 'CUST-1008',
    customerName: 'Ananya Iyer',
    customerPhone: '+91 98401 XXXXX',
    customerAddress: '22, TTK Road, Alwarpet, Chennai 600018',
    appliance: 'Water Purifier',
    applianceId: 'APP-2022',
    brand: 'Pureit',
    model: 'Copper+ Mineral RO',
    issue: 'Water dispensing continuous trickle after button release',
    priority: 'Medium',
    status: 'Closed',
    assignedTechnician: 'V. Prakash (Badge #CH-6610)',
    scheduledDate: '1 week ago',
    created: '8 days ago',
    createdAt: '8 days ago, 14:00',
    aiSummary: 'Solenoid shutoff valve failing to close completely after dispensing copper enriched water.',
    recommendedAction: 'Replaced 24V DC input solenoid valve',
    timeline: [
      { id: 't-241', title: 'Closed', description: 'Valve replaced and leak check passed', timestamp: '16:00', status: 'completed' },
    ],
  },
  {
    id: 'SR-10385',
    customerId: 'CUST-1011',
    customerName: 'Manoj Kumar',
    customerPhone: '+91 98188 XXXXX',
    customerAddress: 'C-40, Lajpat Nagar III, New Delhi 110024',
    appliance: 'Television',
    applianceId: 'APP-2029',
    brand: 'Xiaomi',
    model: 'Smart TV X Series 43',
    issue: 'PatchWall OS boot loop on startup',
    priority: 'Medium',
    status: 'Resolved',
    assignedTechnician: 'Kuldeep Rawat (Badge #DL-5520)',
    scheduledDate: '2 days ago',
    created: '3 days ago',
    createdAt: '3 days ago, 15:00',
    aiSummary: 'System stuck on Mi boot screen after firmware update.',
    recommendedAction: 'Reflashed recovery firmware via USB tool',
    timeline: [
      { id: 't-251', title: 'Resolved', description: 'Firmware successfully restored to stable v14.0.2', timestamp: '17:00', status: 'completed' },
    ],
  },
];
