'use client';

import { FormEvent, useEffect, useState } from 'react';
import { Loader2, Plus, Tv } from 'lucide-react';
import { supabase } from '@/lib/supabase/client';
import { Button } from '@/components/ui/Button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/Card';

type Appliance = { id: string; appliance_type: string; brand: string; model: string; status: string; warranty_end_date: string | null };

export default function MyAppliancesPage() {
  const [appliances, setAppliances] = useState<Appliance[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [type, setType] = useState('washing_machine'); const [brand, setBrand] = useState(''); const [model, setModel] = useState('');
  const load = async () => { const { data: { session } } = await supabase.auth.getSession(); if (!session) return; const response = await fetch('/api/my-appliances', { headers: { Authorization: `Bearer ${session.access_token}` } }); const body = await response.json() as { appliances?: Appliance[] }; setAppliances(body.appliances ?? []); setLoading(false); };
  useEffect(() => { void load(); }, []);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); setError(null); const { data: { session } } = await supabase.auth.getSession(); if (!session) { setError('Please sign in again.'); setSaving(false); return; } const response = await fetch('/api/my-appliances', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${session.access_token}` }, body: JSON.stringify({ applianceType: type, brand, model }) }); if (!response.ok) setError('Unable to save this appliance.'); else { setBrand(''); setModel(''); await load(); } setSaving(false); };
  return <div className="mx-auto max-w-4xl space-y-6"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-blue-600">HomeCare AI</p><h1 className="mt-2 text-3xl font-bold">My appliances</h1><p className="mt-1 text-sm text-slate-500">Register the appliances you want us to support.</p></div><Card><CardHeader><CardTitle>Add appliance</CardTitle></CardHeader><CardContent><form onSubmit={submit} className="grid gap-3 md:grid-cols-4"><select value={type} onChange={(e) => setType(e.target.value)} className="rounded-lg border p-2.5"><option value="washing_machine">Washing machine</option><option value="refrigerator">Refrigerator</option><option value="air_conditioner">Air conditioner</option><option value="television">Television</option><option value="water_purifier">Water purifier</option></select><input value={brand} onChange={(e) => setBrand(e.target.value)} placeholder="Brand" required className="rounded-lg border p-2.5" /><input value={model} onChange={(e) => setModel(e.target.value)} placeholder="Model" required className="rounded-lg border p-2.5" /><Button type="submit" disabled={saving} className="justify-center">{saving ? 'Saving…' : <><Plus className="h-4 w-4" /> Add appliance</>}</Button></form>{error && <p className="mt-3 text-sm text-rose-700">{error}</p>}</CardContent></Card>{loading ? <div className="flex justify-center p-10"><Loader2 className="animate-spin text-blue-600" /></div> : appliances.length === 0 ? <Card><CardContent className="p-10 text-center text-slate-500">Add your first appliance to begin AI support.</CardContent></Card> : <div className="grid gap-4 sm:grid-cols-2">{appliances.map((appliance) => <Card key={appliance.id}><CardContent className="flex gap-3 p-5"><Tv className="mt-0.5 text-blue-600" /><div><p className="font-semibold">{appliance.brand} {appliance.model}</p><p className="mt-1 text-sm capitalize text-slate-500">{appliance.appliance_type.replaceAll('_', ' ')}</p></div></CardContent></Card>)}</div>}</div>;
}
